Add `$isDraft` function unit tests
reviewpad/reviewpad pull request #101
Opened 2022-07-12 09:52 UTC by shay2025

## Description

This pull request introduces `$isDraft` unit tests.

## Related issue

*None*

## Type of change

Improvements (non-breaking change without functionality)

## How was this tested?

Ran `task test` command.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have ran `task check -f` and have no issues

2022-07-12 09:52 UTC, reviewpad-team commented
<!--@annotation-reviewpad-report-->
**Reviewpad Report**

**:information_source: Messages**
* If you are adding or updating a built-in, please do not forget to update the [docs](https://github.com/reviewpad/docs)
* If you have added a new function or action do not forget to include it in the built-in list!

2022-07-12 09:52 UTC, reviewpad-team commented
<!--@annotation-reviewpad-report-->
**Reviewpad Report**

**:information_source: Messages**
* If you are adding or updating a built-in, please do not forget to update the [docs](https://github.com/reviewpad/docs)
* If you have added a new function or action do not forget to include it in the built-in list!

2022-07-12 19:59 UTC, ferreiratiago requested changes
Please have a look at the comments.

2022-07-12 19:59 UTC, ferreiratiago commented on plugins/aladino/functions/isDraft_test.go
> +func TestIsDraftOnNilPullRequest(t *testing.T) {
I'm not sure if this is a use case. I know that we have a condition at `isDraft` with `if pullRequest == nil` but I'm not sure if this is a possibility. Can you please check this?

Also, if this is a possibility then we need to update our builtin in order to make sure that this case is cover (e.g. `description`).

2022-07-12 19:59 UTC, ferreiratiago commented on plugins/aladino/functions/isDraft_test.go
> +    mockedEnv.GetPullRequest().Draft = github.Bool(true)
This is not the correct way. We should use `GetDefaultMockPullRequestDetailsWith`.

```go
mockedPullRequest := mocks_aladino.GetDefaultMockPullRequestDetailsWith(&github.PullRequest{
		Draft: github.Bool(true),
	})
```

2022-07-12 19:59 UTC, ferreiratiago commented on plugins/aladino/functions/isDraft_test.go
> +    mockedEnv.GetPullRequest().Draft = github.Bool(false)
The same here.

2022-07-13 16:13 UTC, ferreiratiago approved these changes

2022-07-14 09:02 UTC, merged