Add unit tests for github paginated request functions
reviewpad/reviewpad pull request #113
Opened 2022-07-12 14:44 UTC by shay2025

## Description

This pull request introduces unit tests for github paginated request related functions.

## Related issue

*None*

## Type of change

Improvements (non-breaking change without functionality)

## How was this tested?

Ran `task test` command.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have ran `task check -f` and have no issues

2022-07-13 12:01 UTC, reviewpad-team commented
<!--@annotation-reviewpad-report-->
**Reviewpad Report**

**:bangbang: Errors**
* **Unconventional commit detected**: 'Add unit tests for github paginated request functions' (678b33b5ed1fd3dae7d525568804648622a36ca3)

2022-07-14 08:57 UTC, ferreiratiago requested changes
Please have a look at the comments.

2022-07-14 08:57 UTC, ferreiratiago commented on utils/github_test.go
> +type result struct {
`result` is too generic. What is is this `result`?

2022-07-14 08:57 UTC, ferreiratiago commented on utils/github_test.go
> +func TestParseNumPagesFromLink_WhenURLHasNoInfo(t *testing.T) {
Suggestion `TestParseNumPagesFromLink_WhenHTTPLinkHeaderHasNoRel`

2022-07-14 08:57 UTC, ferreiratiago commented on utils/github_test.go
> +func TestParseNumPagesFromLink_WhenParseURLFails(t *testing.T) {
Suggestion `TestParseNumPagesFromLink_WhenHTTPLinkHeaderIsInvalid`

2022-07-14 08:57 UTC, ferreiratiago commented on utils/github_test.go
> +func TestParseNumPagesFromLink_WhenPageQueryIsNotPresentInURL(t *testing.T) {
Suggestion `TestParseNumPagesFromLink_WhenHTTPLinkHeaderHasNoQueryParamPage`

2022-07-14 08:57 UTC, ferreiratiago commented on utils/github_test.go
> +func TestParseNumPagesFromLink_WhenNumPagesParseIntFails(t *testing.T) {
Suggestion `TestParseNumPagesFromLink_WhenHTTPLinkHeaderHasInvalidQueryParamPage`

2022-07-14 08:57 UTC, ferreiratiago commented on utils/github_test.go
> +func TestParseNumPages_WhenNoLinkIsProvided(t *testing.T) {
Suggestion `TestParseNumPages_WhenHTTPLinkHeaderIsNotProvided `

2022-07-14 08:57 UTC, ferreiratiago commented on utils/github_test.go
> +	// The number of pages are given in the url query "page"
Suggestion `// the number of pages is provided in the url query parameter "page"`

2022-07-14 08:57 UTC, ferreiratiago commented on utils/github_test.go
> +	// The number of pages are given in the url query "page"
This comment is not necessary.

2022-07-14 08:57 UTC, ferreiratiago commented on utils/github_test.go
> +	// The number of pages are given in the url query "page"
Suggestion `// the number of pages is provided in the url query parameter "page"`

2022-07-14 09:19 UTC, shay2025 commented on utils/github_test.go
> +type result struct {
`result` is an object that results of the paginated request

2022-07-14 09:27 UTC, ferreiratiago approved these changes

2022-07-14 09:30 UTC, merged