fix: yaml multiline, issue #89
reviewpad/reviewpad pull request #130
Opened 2022-07-14 15:34 UTC by versoul

## Description

Fix adds support multiline strings in yaml config

## Related issue

Closes [issue #89](https://github.com/reviewpad/reviewpad/issues/89)

## Type of change

Bug fix (non-breaking change which fixes an issue)

## How was this tested?

Ran `task test` command.
Use rewiewpad as CLI with this config part
```yaml
workflows:
  - name: label-pull-request-with-size
    description: Label pull request with size
    if:
      - rule: isSmall
         extra-actions:
         - >
            $addLabel("small
             multiline")
      - rule: isMedium
         extra-actions:
           - >
             $addLabel("medium
              multiline")
       - rule: isLarge
          extra-actions:
          - >
             $addLabel("large
              multiline")
```

## Checklist

- [x] I have performed a self-review of my code
- [x] I have ran `task check -f` and have no issues

2022-07-15 07:58 UTC, ferreiratiago requested changes
Please have a look at the suggestions. Also, if you could take the time to write all uses cases for `Parse` (in order to get the maximum coverage) that would be great :)

2022-07-15 07:58 UTC, ferreiratiago commented on lang/aladino/parse_test.go
> +func TestParse(t *testing.T) {
This test can be split into two different use cases, e.g. `TestParse_WhenSingleLine` and `TestParse_WhenMultilineLine`.

2022-07-15 07:58 UTC, ferreiratiago commented on lang/aladino/parse_test.go
> +	assert.Nil(t, err)
I'm afraid that testing that `err` is not nil is not enough. We need to make sure that the returned `Expr` is the correct one. Can you please make sure of that? Thanks.

2022-07-17 12:17 UTC, versoul commented
@ferreiratiago test fixed, I think these test cases are enough to cover this issue because after reading yaml we get either a string or a string with a hyphen at the end, which caused the problem before

2022-07-19 15:42 UTC, marcelosousa commented
@versoul are you sure you pushed the latest changes? the comment from @ferreiratiago seems to apply still.

Also, please rebase with the latest version of main so that we keep the PR up to date. 

Thanks!

2022-07-19 15:52 UTC, reviewpad-team commented
<!--@annotation-reviewpad-report-->
**Reviewpad Report**

**:warning: Warnings**
* This pull request does not have linear history - please fix this!

**:bangbang: Errors**
* **Unconventional commit detected**: 'Merge remote-tracking branch 'origin/fix/yaml_multiline' into fix/yaml_multiline' (c483bcb9c8408ff348519fce75a96d764877bb43)

**:information_source: Messages**
* If you are adding or updating a built-in, please do not forget to update the [docs](https://github.com/reviewpad/docs)
* It looks like you modified both functions and actions. Is that intentional?
* If you have added a new function or action do not forget to include it in the built-in list!

2022-07-19 15:54 UTC, versoul commented
@marcelosousa done, and yes latest changes pushed

2022-07-19 16:05 UTC, marcelosousa requested changes
Last changes requested before approval and merge.

2022-07-19 16:05 UTC, marcelosousa commented on lang/aladino/parse_test.go
> +	wantExpr = &FunctionCall{
Same comment as above.

2022-07-19 16:32 UTC, marcelosousa approved these changes

2022-07-19 16:32 UTC, merged