test: lang aladino env unit tests
reviewpad/reviewpad pull request #131
Opened 2022-07-14 15:58 UTC by shay2025

## Description

This pull request introduces unit tests for `lang/aladino/env`.

## Related issue

*None*

## Type of change

Improvements (non-breaking change without functionality)

## How was this tested?

Ran `task test` cmd.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have ran `task check -f` and have no issues

2022-07-15 09:40 UTC, ferreiratiago requested changes
Please review the use of `reflect.DeepEqual` to make sure it's the right function to compare the output.

2022-07-20 14:28 UTC, marcelosousa requested changes
Thanks for this! I've left comments in the diff.

2022-07-20 14:28 UTC, marcelosousa commented on lang/aladino/env_test.go
> +// The MockDefaultEnv function to create a mocked default env, it uses the NewEvalEnv which is the function we wish to test
This comment is a bit confusing. From the name of the function, we should be testing NewEval but it's only called indirectly through the MockDefaultEnv. It seems that what we are really testing is the MockDefaultEnv.

2022-07-20 14:28 UTC, marcelosousa commented on lang/aladino/env_test.go
> +func TestNewEvalEnv_WhenNewFileFails(t *testing.T) {
Same comment from previous function applies here and in the next test functions.

2022-07-22 12:00 UTC, marcelosousa reviewed
Please check the comments.

2022-07-22 12:04 UTC, marcelosousa commented on lang/aladino/mocks.go
> +var DefaultContext = context.Background()
please rename to DefaultMockX

2022-07-22 14:34 UTC, marcelosousa approved these changes
🙌

2022-07-22 14:35 UTC, merged