feat: :sparkles: comment dry run report
reviewpad/reviewpad pull request #158
Opened 2022-07-24 06:01 UTC by zolamk

## Description

- send dry run report

## Related issue

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?

1. Run Reviewpad in dry run mode checked the results were as expected

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have ran `task check -f` and have no issues

2022-07-24 06:01 UTC, reviewpad-team commented
<!--@annotation-reviewpad-report-->
**Reviewpad Report**

**:information_source: Messages**
* @marcelosousa: you are being notified because critical code was modified

2022-07-25 17:31 UTC, marcelosousa requested changes
Many thanks for this contribution 🙌 ! Please check the comment in runner.go which involves a substantial change in this pull request.

2022-07-25 17:31 UTC, marcelosousa commented on lang/aladino/report.go
> +		sb.WriteString("**Reviewpad Report** (Reviewpad ran in dry-run mode because reviewpad.yml has changed)\n\n")
We can actually pass a different input file. Instead of reviewpad.yml lets say that "because configuration file has changed"

2022-07-25 17:31 UTC, marcelosousa commented on runner.go
> +	} else {
This can be problematic because we can run Reviewpad as a CLI in dry-run in which case the report will be added to the pull request. I think we need to introduce a new boolean flag to signal when the configuration file was changed.

2022-07-25 18:08 UTC, zolamk commented on runner.go
> +	} else {
should we also allow setting the new `reviewpadChanged` boolean from the cli?

2022-07-25 18:20 UTC, zolamk commented on runner.go
> +	} else {
Also, should it run in dry-run mode if the `reviewpadChanged` bool is true, or should we let the caller of the run function determine that?

2022-07-26 07:46 UTC, marcelosousa commented on runner.go
> +	} else {
I think the boolean variable should be called something on the lines `safeMode` instead of `reviewpadChanged`. 

I don't think there's need for the new boolean to be passed in the CLI for now. 

Regarding the second question, yes, it's a pre-condition that if the new boolean is true then dry-run needs to be true as well.

2022-07-26 10:04 UTC, marcelosousa requested changes
Please check the style issue!

2022-07-26 10:04 UTC, marcelosousa commented on lang/aladino/report.go
> +
Please remove this empty line. Same in the rest of the pull request!

2022-07-26 14:31 UTC, marcelosousa commented
@zolamk can you please update with the base branch? The build is failing at the moment.

2022-07-26 14:35 UTC, zolamk commented
> @zolamk can you please update with the base branch? The build is failing at the moment.

I am rebasing at the moment

> @zolamk can you please update with the base branch? The build is failing at the moment.

I've rebased and updated the tests.

2022-07-26 15:24 UTC, marcelosousa requested changes
Check the comments in the runner.go. Thanks!

2022-07-26 15:24 UTC, marcelosousa commented on runner.go
> +		return nil, fmt.Errorf("reviewpad can only be run in dry-run when in safe mode")
The error message doesn't seem correct because you can run reviewpad with dry-run as true and safe mode as false. What you mean here is: "when reviewpad is running in safe mode, it must also run in dry-run".

2022-07-26 16:27 UTC, zolamk commented on runner.go
> +	}
That was the first thing I tried too, but from what I can tell the aladino report is generated when the program is executed not during evaluation, which means in dry run mode since the program isn't executed there is no report generated and calling the `Report` method on the interpreter would just say `No workflows activated` [https://github.com/reviewpad/reviewpad/blob/62b1be11caa894e5cf04a252d72eae3cc807f29f/lang/aladino/interpreter.go#L131-L152](https://github.com/reviewpad/reviewpad/blob/62b1be11caa894e5cf04a252d72eae3cc807f29f/lang/aladino/interpreter.go#L131-L152)

2022-07-26 16:29 UTC, zolamk commented on runner.go
> +	}
What I see as a possible solution is during evaluation we could keep another report maybe called `EvaulationReport` and during `safeMode` we could have an `EvaluationReport` method on the interpreter and use that for the report. Sounds good?

2022-07-26 17:28 UTC, marcelosousa commented on runner.go
> +	}
I think it's confusing to have multiple reports. I think it's more elegant to pass the control variables to the interpreter environment and to use those variables inside the ExecProgram and ExecStatement interface method implementations. Does that sound good?

2022-07-26 17:36 UTC, zolamk commented on runner.go
> +	}
Yeah, that's a much better solution.

2022-07-27 14:33 UTC, marcelosousa requested changes

2022-07-27 14:33 UTC, marcelosousa commented on runner.go
> +	if safeMode {
This conditional is a no-op.

2022-07-27 14:33 UTC, marcelosousa commented on lang/aladino/interpreter.go
> +	return i.Env.GetReport().SendReport(env.GetCtx(), env.GetSafeMode(), mode, env.GetPullRequest(), env.GetClient())
This change increases the complexity of the code quite a bit. I think that abstracting the code with the `SendReport` makes things harder. I think we should revert that change.

Also, I think this is the only place where you really need to retrieve the `safeMode` boolean so I would prefer if you passed it as an argument to the `Report` function instead of adding it to the environment.

2022-07-27 14:33 UTC, marcelosousa commented on runner.go
> +	err = aladinoInterpreter.Report(reviewpadFile.Mode)
There's an issue with simply calling Report here. If we are running in safe mode then we want to add the report to the pull request, but if are not running in safe mode **and** in dry run, the comment will be added to the pull request and that is not intended.

2022-07-27 20:52 UTC, marcelosousa reviewed
I think this is the last round of comments before it is ready to merge! Thank you so much @zolamk 🚀

2022-07-27 20:52 UTC, marcelosousa commented on runner.go
> +	// or not in dry run mode
this comment is not necessary :-)

2022-07-27 20:52 UTC, marcelosousa commented on lang/aladino/interpreter.go
> +		return AddReportComment(i.Env, report)
```suggestion
		return AddReportComment(env, report)
```

2022-07-27 20:52 UTC, marcelosousa commented on lang/aladino/interpreter.go
> +	return UpdateReportComment(i.Env, *comment.ID, report)
```suggestion
	return UpdateReportComment(env, *comment.ID, report)
```

2022-07-28 07:54 UTC, marcelosousa approved these changes

2022-07-28 07:56 UTC, merged

2022-07-28 07:56 UTC, marcelosousa commented
Many thanks for this contribution @zolamk 🚀