Add  built-in utility function `$reviewerStatus`
reviewpad/reviewpad pull request #170
Opened 2022-07-26 14:28 UTC by thedevsaddam

## Description

This pull request introduces a built-in utility function `$reviewerStatus`.

## Related issue

Closes #160

## Type of change

Improvements (non-breaking change without functionality)

## How was this tested?

Ran `task test` command and also checked  coverage using `task coverage`

## Checklist

- [x] I have performed a self-review of my code
- [x] I have ran `task check -f` and have no issues

2022-07-26 14:54 UTC, marcelosousa requested changes
Thanks for this contribution 🙌 ! Please check the comments in diff 😄

2022-07-26 14:54 UTC, marcelosousa commented on plugins/aladino/functions/reviewerStatus.go
> +func reviewerStatusCdoe(e aladino.Env, args []aladino.Value) (aladino.Value, error) {
There's a typo here: `reviewerStatusCode`

2022-07-26 14:54 UTC, marcelosousa commented on plugins/aladino/functions/reviewerStatus.go
> +// reviewerStatusCdoe return the lastest review status (neutral, requested_changes, approved) of the reviewerLogin on a pull request
No need for this comment as the documentation already exists in github.com/reviewpad/docs.

2022-07-26 14:54 UTC, marcelosousa commented on plugins/aladino/functions/reviewerStatus.go
> +// ReviewerStatus return the lastest review status of reviewer on a pull request
No need for this comment

2022-07-26 14:54 UTC, marcelosousa commented on plugins/aladino/functions/reviewerStatus.go
> +// contain all the available reviewer status states
No need for this comment :)

2022-07-26 14:54 UTC, marcelosousa commented on plugins/aladino/functions/reviewerStatus.go
> +	ReviewerStatusStateRequestApproved string = "APPROVED"
As far as I can see, these constants are not used anywhere.

2022-07-26 14:54 UTC, marcelosousa commented on plugins/aladino/functions/reviewerStatus.go
> +
style: Remove this empty line.

2022-07-26 14:54 UTC, marcelosousa commented on plugins/aladino/functions/reviewerStatus.go
> +
style: Remove this empty line.

2022-07-26 14:54 UTC, marcelosousa commented on utils/github.go
> +// GetPullRequestReviews fetch pull request reviews
No need for this comment.

2022-07-26 14:54 UTC, marcelosousa commented on plugins/aladino/functions/reviewerStatus.go
> +	for _, r := range reviews {
Please rename `r` to a more readable variable name, e.g. `review`.

2022-07-26 14:54 UTC, marcelosousa commented on plugins/aladino/functions/reviewerStatus.go
> +		if *r.User.Login != *&reviewerLogin.Val {
We can't trust github that r.User is always different than nil. Please add this check and in such case, skip that review.

I don't get why you need to `*&`. It should suffice to do `reviewerLogin.Val`.

2022-07-26 14:54 UTC, marcelosousa commented on plugins/aladino/functions/reviewerStatus_test.go
> +			),
This code seems duplicated from L27-L33?

2022-07-26 15:35 UTC, ferreiratiago requested changes
Thanks for the contribution 🙌🏼 Please have a look at the suggested comments.

2022-07-26 15:35 UTC, ferreiratiago commented on plugins/aladino/functions/reviewerStatus.go
> +	ReviewerStatusStateRequestApproved string = "APPROVED"
They are being used on the [switch statement](https://github.com/reviewpad/reviewpad/pull/170/files#diff-89c5cf108ac0f813e834be23aa068710bf3a3ee094eb1187ef96705c2cf5e633R49). However, `ReviewerStatusStateCommented` is not being used. Also `ReviewerStatusStateRequestApproved` could be called `ReviewerStatusStateApproved` (not sure if approving the pull request is requesting anything) :)

2022-07-26 15:35 UTC, ferreiratiago commented on plugins/aladino/functions/reviewerStatus_test.go
> +func TestReviewerStatusRequestFails(t *testing.T) {
Following conventions usually we do `TestFUNCTION_WhenSCENARIO`. In this case it would be `TestReviewerStatus_WhenRequestFails`.

2022-07-26 15:35 UTC, ferreiratiago commented on plugins/aladino/functions/reviewerStatus_test.go
> +func TestReviewerStatusNeutral(t *testing.T) {
Suggestion `TestReviewerStatus_WhenStateUnknown`

2022-07-26 15:35 UTC, ferreiratiago commented on plugins/aladino/functions/reviewerStatus_test.go
> +func TestReviewerStatusApproved(t *testing.T) {
Suggestion `TestReviewerStatus_WhenStateApproved`

2022-07-26 15:35 UTC, ferreiratiago commented on plugins/aladino/functions/reviewerStatus.go
> +	reviews, err := utils.GetPullRequestReviews(e.GetCtx(), e.GetClient(), owner, repo, prNum, &github.ListOptions{})
Are these `reviews` ordered ascending by date? We need to make sure of that from github api. This is to make sure that if a review makes Ra -> Rb -> Rc, his review state is the one from the last review, i.e. Rc.

2022-07-26 15:35 UTC, ferreiratiago commented on plugins/aladino/functions/reviewerStatus_test.go
> +			State: github.String("COMMENTED"),
I would suggest to remove this element or change it's `state` value to `CHANGES_REQUESTED`. This is to make it clear which `state` is actually being returned, in this case is it from the first element or the last one?

2022-07-26 15:35 UTC, ferreiratiago commented on plugins/aladino/functions/reviewerStatus_test.go
> +func TestReviewerStatusRequestedChanges(t *testing.T) {
Suggestion `TestReviewerStatus_WhenStateRequestedChanges `

2022-07-26 15:35 UTC, ferreiratiago commented on plugins/aladino/functions/reviewerStatus.go
> +const (
Can you add a link to github documentation proving that these states are the only ones available?

2022-07-26 15:35 UTC, ferreiratiago commented on utils/github_test.go
> +func TestGetPullRequestReviewsFails(t *testing.T) {
Suggestion `TestGetPullRequestReviews_WhenRequestFails`.

2022-07-26 15:35 UTC, ferreiratiago commented on utils/github_test.go
> +func TestGetPullRequestReviewsWithCommentedState(t *testing.T) {
Suggestion `TestGetPullRequestReview`. Not need to specify that it is the commented state.

2022-07-26 16:05 UTC, ferreiratiago commented on plugins/aladino/functions/reviewerStatus.go
> +	reviews, err := utils.GetPullRequestReviews(e.GetCtx(), e.GetClient(), owner, repo, prNum, &github.ListOptions{})
Just check and the order is [chronological order](https://docs.github.com/en/rest/pulls/reviews#list-reviews-for-a-pull-request)

2022-07-26 16:57 UTC, thedevsaddam commented on plugins/aladino/functions/reviewerStatus.go
> +const (
Unfortunately, I didn't find any solid documentation for the response state values.
https://docs.github.com/en/rest/pulls/reviews#create-a-review-for-a-pull-request--parameters
Here in the response schema, it mentioned the state as string (no ENUM example) and in the response example shows some state.

Note: I did find 3 of the review state from Github review UI. I used the UI to change states and used the Github client library to get the states.
States that I found:
- COMMENTED
- CHANGES_REQUESTED
- APPROVED

2022-07-26 16:59 UTC, thedevsaddam commented on plugins/aladino/functions/reviewerStatus.go
> +	ReviewerStatusStateRequestApproved string = "APPROVED"
As the constants are not used anywhere, I've removed them.

2022-07-26 17:06 UTC, thedevsaddam commented on plugins/aladino/functions/reviewerStatus_test.go
> +func TestReviewerStatusRequestFails(t *testing.T) {
Thank you so much for pointing out the conventions :)

2022-07-26 17:07 UTC, thedevsaddam commented on plugins/aladino/functions/reviewerStatus.go
> +		if *r.User.Login != *&reviewerLogin.Val {
Thank you so much for the feedback. I've updated accordingly.

2022-07-26 17:32 UTC, thedevsaddam commented
I've updated the changes accordingly.

Thank you guys for the review and feedbacks. 

@marcelosousa Need to update the [docs](https://github.com/reviewpad/docs/pull/12/files)

2022-07-27 14:03 UTC, marcelosousa requested changes
I made some code suggestions. Please check as the github editor for the suggestions is probably messing the white space formats.

2022-07-27 16:12 UTC, marcelosousa commented on plugins/aladino/functions/reviewerStatus_test.go
> +func TestReviewerStatus_whenRequestFails(t *testing.T) {
typo: when -> When

2022-07-27 16:15 UTC, marcelosousa approved these changes
Ready to merge. Tested locally. @thedevsaddam please check the typo in the unit tests and rebase with the base if needed. Thank you 🙌

2022-07-27 16:21 UTC, merged

2022-07-27 16:23 UTC, thedevsaddam commented
Thank you so much guys for the feedbacks. This will definitely help me to improve my thought process on the next pull request!