test: add unit tests for engine program
reviewpad/reviewpad pull request #173
Opened 2022-07-26 15:47 UTC by shay2025

## Description

This pull request introduces unit tests for engine program.

## Related issue

*None*

## Type of change

Improvements (non-breaking change without functionality)

## How was this tested?

Ran `task test` cmd.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have ran `task check -f` and have no issues

2022-07-26 17:32 UTC, marcelosousa requested changes

2022-07-26 17:32 UTC, marcelosousa commented on engine/program_internal_test.go
> +				Code: "$actionC()",
Since you are re-using the `workflow` and the `rules` variables, it makes sense to create a variable `code`, `metadata`, etc to use here and in L30, L31, etc.

2022-07-27 00:24 UTC, shay2025 commented on engine/program_internal_test.go
> +				Code: "$actionC()",
@marcelosousa is it enough to instead only have a `statement` variable?
```
statement := &Statement{
    Code: "$actionC()",
    Metadata: &Metadata{
	    Workflow: PadWorkflow{
		    Name: "test-workflow-C",
	    },
	    TriggeredBy: []PadWorkflowRule{
		    {Rule: "test-rule-C"},
	    },
    },
}
program := &Program{
    Statements: []*Statement{statement},
}

wantProgram := &Program{
    Statements: []*Statement{
	    statement,
	    {
		    Code: "$actionB()",
		    Metadata: &Metadata{
			    Workflow:    workflow,
			    TriggeredBy: rules,
		    },
	    },
    },
}
```

2022-07-27 08:24 UTC, marcelosousa approved these changes
Pair reviewed with @shay2025 .

2022-07-27 08:24 UTC, merged