test: add unit tests for engine loader
reviewpad/reviewpad pull request #174
Opened 2022-07-27 00:11 UTC by shay2025

## Description

This pull request introduces unit tests for engine loader.
To be able to do http mocks, it's proposed the use of https://github.com/jarcoal/httpmock.

## Related issue

*None*

## Type of change

Improvements (non-breaking change without functionality)

## How was this tested?

Ran `task test` cmd.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have ran `task check -f` and have no issues

2022-08-01 11:18 UTC, marcelosousa requested changes
Please move the `resources/test` files to `testdata` folder.

Please rebase with the base branch.

2022-08-03 10:47 UTC, ferreiratiago requested changes
My suggestion here is to refactor the tests taking into account table testing and the creating of file mocks. Please have a look at the comments.

2022-08-03 10:47 UTC, ferreiratiago commented on engine/loader_internal_test.go
> +}
It's a bit confusing that this file is called `internal` and tests private and public functions. Also, may I suggest to convert this to not internal and use table testing?

```
func TestLoad() {
	"when parse error"
	"when success"
}

func TestLoad_Imports() {
	"when import file not found"
	"when import file is corrupt"
	"when import file fails to parse"
	"when import file is already loaded"
	"when import file imports other files"
	"when cyclic dependency"
}

func TestLoad_Transform() {
	"for actions"
	"for extra actions"
}
```

2022-08-03 10:47 UTC, ferreiratiago commented on engine/loader_internal_test.go
> +}
I would also suggest to create an input file to each one of the use cases on `testdata/loader`.

For instance, the following files could be added:
* reviewpad_with_parse_error.yml
* reviewpad_with_import_not_found.yml
* reviewpad_with_import_corrupted.yml
* ...
For the testing input maybe we can add a folder named `testdata/loader/transform` and add the files for input and outputs.
* reviewpad_transform_action.input.yml
* reviewpad_transform_action.output.yml

This will help to reduce the test sizes and to remove the added mocks on `mocks.go`.

WDYT?

2022-08-03 16:26 UTC, shay2025 commented on engine/loader_internal_test.go
> +}
@ferreiratiago firstly, thanks for the suggestions!
After thinking about it a bit:
1. Maybe we should apply the approach of `xyz_test.go` for external API and `xyz_internal_test.go` for internal API. WDYT?
2. Also I didn't quite understand the appoach you suggested for TDT. Shouldn't it be something like:
```
func TestParser() {
	"when error"
	"when success"
}

func TestTransform() {
      "for actions"
      "for extra actions"
}

func TestLoadImport() {
	"when import file not found"
	"when import file fails to parse"
	"when success"
}

func TestInlineImports() {
	"when import file not found"
	"when cyclic dependency"
        "when import file is already loaded"
        "when import file imports other files"
}

func TestLoad() {
	"when parse error"
	"when success"
}
```

2022-08-03 17:19 UTC, ferreiratiago commented on engine/loader_internal_test.go
> +}
My suggestion was not following `_internal_`. That's why all suggestion are `TestLoad_X`. 

I have thought about the tests answering the question **How should the loader behave based on the provided file?**, mainly:
* when the file has a parsing error
* when the file has an import of a non existing file
* when the file has an import of a corrupted file
* when the file has an import of a file with a parsing error
* when the file has chain of imports
* when the file has cyclic imports
* when the file has no issues

But this does not cover all cases. For instance, the use cases for transform do not get covered here. That's why I have suggested the following scenarios:
* when the file requires action transformation
* when the file requires extra action transformation

The next step was to organize these tests into categories, such as `_Imports` and `_Transform`.

For black box tests is not really important the `inlineImports` or the `transform` function. What's really important is that whenever I provided a file with a certain type of characteristics  (e.g. parsing error), the output will always be the same.

Saying that I think we should focus on how loader should behave regardless of its implementation details.

2022-08-04 07:54 UTC, shay2025 commented on engine/loader_internal_test.go
> +}
Yes but we decided previously we would also test implementation that's why we were adding `_internal_` keyword into the test file name because by convention if you decide to do internal API tests you should introduce `_internal_` keyword to the test file name in order to flag them as being more brittle. What I would suggest indeed is to separe external API tests from internal API tests but this would create many more files.

2022-08-04 16:16 UTC, shay2025 commented on engine/loader_test.go
> +				wantReviewpadFile.Imports = []engine.PadImport{}
@ferreiratiago following the code comment hightlighted, shouldn't this:
https://github.com/reviewpad/reviewpad/blob/d867d9e1c1bedf9ac7041f266333d0beaf0d5fac/engine/loader.go#L165-L166
be:
```
	// reset all imports
	file.Imports = []PadImport(nil)
```

2022-08-04 21:37 UTC, ferreiratiago requested changes
We are going into the right direction. Just need to improve the mock files to make sure we don't have unnecessary code.

2022-08-04 21:37 UTC, ferreiratiago commented on engine/loader_test.go
> +		// Fail
No need for this comment.

2022-08-04 21:37 UTC, ferreiratiago commented on engine/loader_test.go
> +		"when the file has an import of a nonexisting file": {
```suggestion
		"when the file imports a nonexistent file": {
```

2022-08-04 21:37 UTC, ferreiratiago commented on engine/loader_test.go
> +			inputReviewpadFilePath: "../testdata/engine/loader/reviewpad_with_import_of_nonexisting_file.yml",
```suggestion
			inputReviewpadFilePath: "../testdata/engine/loader/reviewpad_with_import_of_nonexistent_file.yml",
```

2022-08-04 21:37 UTC, ferreiratiago commented on engine/loader_test.go
> +		// Pass
No need for this comment.

2022-08-04 21:37 UTC, ferreiratiago commented on engine/loader_test.go
> +		"when the file imports other files": {
```suggestion
		"when the file has import chains": {
```

2022-08-04 21:37 UTC, ferreiratiago commented on engine/loader_test.go
> +		},
These files should be inside a folder called `transform` under `testdata/engine/loader/transform`.

2022-08-04 21:37 UTC, ferreiratiago commented on engine/loader_test.go
> +}
This code is a bit confusing because we have to deal with both cases when there's error and don't. What do you think about splitting those cases into different loops?

```go
	for name, test := range tests {
		if test.wantErr == "" {
			continue
		}

		t.Run(name, func(t *testing.T) {
			// code for testing when error is expected
		})
	}

	for name, test := range tests {
		if test.wantErr != "" {
			continue
		}

		t.Run(name, func(t *testing.T) {
			// code for testing when no error is expected
		})
	}
```

2022-08-04 21:37 UTC, ferreiratiago commented on testdata/engine/loader/reviewpad_after_action_transform.yml
> +      - '$merge("merge")'
I understand the need of theses files and I'm all for it. My suggestion is to reduce the file content to only what it's actually needed.

```suggestion
api-version: reviewpad.com/v3.x

rules:
  - name: tautology
    kind: patch
    spec: true

workflows:
  - name: merge
    if:
      - rule: tautology
    then:
      - $merge("merge")
```

2022-08-04 21:37 UTC, ferreiratiago commented on testdata/engine/loader/reviewpad_after_action_transform.yml
> +      - '$merge("merge")'
Please review all mock files to make sure we only have what's needed.

2022-08-04 21:37 UTC, ferreiratiago commented on testdata/engine/loader/reviewpad_appended.yml
> +      - '$merge("merge")'
Here's a good example. This file is too big. There's no need for that. Suggestion:

For the file `testdata/engine/loader/reviewpad_with_no_imports.yml`.

```
api-version: reviewpad.com/v3.x

rules:
  - name: is-medium
    kind: patch
    spec: $size() > 30 && $size() <= 100

workflows:
  - name: medium
    if:
      - rule: is-medium
    then:
      - $addLabel("medium")
```

And then for file `testdata/engine/loader/reviewpad_with_one_import.yml`

```yml
api-version: reviewpad.com/v3.x

imports:
  - url: https://foo.bar/reviewpad_with_no_imports.yml

rules:
  - name: is-large
    kind: patch
    spec: $size() > 100

workflows:
  - name: large
    if:
      - rule: is-large
    then:
      - $addLabel("large")
```

And then, this one become much simpler.

```yml
api-version: reviewpad.com/v3.x

rules:
  - name: is-medium
    kind: patch
    spec: $size() > 30 && $size() <= 100
  - name: is-large
    kind: patch
    spec: $size() > 100

workflows:
  - name: medium
    if:
      - rule: is-medium
    then:
      - $addLabel("medium")
  - name: large
    if:
      - rule: is-large
    then:
      - $addLabel("large")
```

We can't forget that each one of these files need to be maintained.

2022-08-04 22:35 UTC, shay2025 commented on engine/loader_test.go
> +		},
By that logic, we should also do the same for other internal functions that are being used in `Load`. I don't see the need for this.

2022-08-04 22:36 UTC, shay2025 commented on engine/loader_test.go
> +}
How is it confusing?
By that same logic, we should also do the same for the input and output reviewpad file when it is expected one and when it isn't.

2022-08-04 22:38 UTC, shay2025 commented on testdata/engine/loader/reviewpad_appended.yml
> +      - '$merge("merge")'
I made this file so big on purpose because here we are testing all the appends: `appendLabels`, `appendGroups` and `appendRules`. This is to take into account everything.

2022-08-08 10:33 UTC, ferreiratiago approved these changes
Some minor comments but all good 👍🏼

2022-08-08 10:33 UTC, ferreiratiago commented on engine/loader_test.go
> +				// Shuts down the mock environment, removes the registered mocks and returns the mock environment to its initial state.
No need for these comments.

2022-08-08 10:33 UTC, ferreiratiago commented on engine/testdata/loader/reviewpad_appended.yml
> +# We use this file for as mocked reviewpad file output for the test with the use case of when a file has import chains.
No need for this comment.

2022-08-08 10:33 UTC, ferreiratiago commented on engine/testdata/loader/reviewpad_appended.yml
> +# This file should result in the merge of the files:
```suggestion
# This file is the result of merging the following files:
```

2022-08-08 13:11 UTC, merged