feat/bultin hasMissingReviews
reviewpad/reviewpad pull request #198
Opened 2022-07-29 11:23 UTC by ferreiratiago

- refactor: fail on mockEnvWith function instead of returning error
- feat: add builtin hasMissingReviews

## Description

## Related issue

## Type of change

## How was this tested?

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or that my feature works 
- [ ] I have ran `task check -f` and have no issues

2022-07-29 13:28 UTC, marcelosousa commented
@ferreiratiago please open a PR with reviewpad/docs with the specification.

2022-07-29 13:54 UTC, marcelosousa requested changes
First pass: did not look into tests yet.

2022-07-29 13:54 UTC, marcelosousa commented on plugins/aladino/functions/hasMissingReviews.go
> +	log.Printf("Running builtin hasMissingReviewsCode")
please remove this log

2022-07-29 13:54 UTC, marcelosousa commented on plugins/aladino/functions/hasMissingReviews.go
> +	}
I don't see the need for the comments and the split of the conditionals:
```suggestion
	if len(requestedTeams) > 0 || len(requestedUsers) > 0  {
		return aladino.BuildBoolValue(true), nil
	}
```

2022-07-29 13:54 UTC, marcelosousa commented on plugins/aladino/functions/hasMissingReviews.go
> +		log.Printf("[WARN] No commits found for PR %s/%s#%d.", owner, repo, prNum)
I think it would be best to use `log.Infof`.

2022-07-29 13:54 UTC, marcelosousa commented on plugins/aladino/functions/hasMissingReviews.go
> +	// When there are no commits, there's nothing to review.
No need for the comment.

2022-07-29 13:54 UTC, marcelosousa commented on plugins/aladino/functions/hasMissingReviews.go
> +	latestCommitDate := commits[len(commits)-1].Commit.Committer.Date
{HIGH}: This strategy is a bit brittle because commit dates can be changed. In fact, an user could put the commit date to the future.

We should be checking the date of last push event. I don't think it makes sense to fix this right now as it is quite a big change but please add it as a FIXME and open an issue.

2022-07-29 13:54 UTC, marcelosousa commented on plugins/aladino/functions/hasMissingReviews.go
> +	// However, it could make sense to check only the author last commit.
No need for this code comment.

2022-07-29 13:54 UTC, marcelosousa commented on plugins/aladino/functions/hasMissingReviews.go
> +		userLogin := review.User.GetLogin()
This is a general comment but it's likely that there's an edge case where the user is nil. We can't trust the code host :(

2022-07-29 13:54 UTC, marcelosousa commented on plugins/aladino/functions/hasMissingReviews.go
> +		}
For readability, please move this conditional to the beginning of the loop and drop the code comment.

2022-07-29 13:54 UTC, marcelosousa commented on plugins/aladino/functions/hasMissingReviews.go
> +		reviewValidityByUser[review.User.GetLogin()] = review.SubmittedAt.After(*latestCommitDate)
```suggestion
		reviewValidityByUser[userLogin] = true
```

It's unclear to me if we shouldn't be checking if the status of the review is approved or requested changes. The built-in is suppose to check if there is no review at all?

2022-07-29 13:54 UTC, marcelosousa commented on plugins/aladino/functions/hasMissingReviews.go
> +	reviewValidityByUser := make(map[string]bool)
Suggestion for the variable name: `changedAfterLastReview`.

2022-07-29 13:54 UTC, marcelosousa commented on plugins/aladino/functions/hasMissingReviews.go
> +	// If there is at least one user with a invalid review, return true.
No need for the comment.

2022-07-29 15:17 UTC, shay2025 approved these changes
Minor thoughts

2022-07-29 15:17 UTC, shay2025 commented on plugins/aladino/functions/hasMissingReviews_test.go
> +							)
For consistency with other tests, maybe it should be `GetPullRequestReviewsRequestFailed`.

2022-07-29 15:17 UTC, shay2025 commented on plugins/aladino/functions/hasMissingReviews_test.go
> +			wantError: "RequestFail_GetPullRequestReviews",
Same as L88.

2022-07-29 15:17 UTC, shay2025 commented on plugins/aladino/functions/hasMissingReviews_test.go
> +											Login: github.String("john"),
In the defined mocks in `lang/aladino/mocks.go`,  the pull request author is called "john".  Is this on purpose or is there the need to rewrite the author of the pull request in order that we ensure that the author isn't one of the requested reviewers?
```
...
mock.WithRequestMatchHandler(
    mock.GetReposPullsByOwnerByRepoByPullNumber,
    http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
        w.Write(mock.MustMarshal(
	    aladino.GetDefaultMockPullRequestDetailsWith(&github.PullRequest{
                    User: &github.User{Login: github.String("john")},
		    RequestedReviewers: []*github.User{{
			    Login: github.String("jane"),
                    }},
		    RequestedTeams: []*github.Team{},
	    }),
        ))
    }),
),
...
```

2022-07-29 15:17 UTC, shay2025 commented on plugins/aladino/functions/hasMissingReviews_test.go
> +											Login: github.String("john"),
Same as L188

2022-07-29 16:52 UTC, ferreiratiago commented on plugins/aladino/functions/hasMissingReviews.go
> +func hasMissingReviewsCode(e aladino.Env, _ []aladino.Value) (aladino.Value, error) {
That's a good point. This means that the name is not the best one. The idea of this builtin is to get know if the author is waiting for a review.

2022-07-29 16:52 UTC, ferreiratiago commented on plugins/aladino/functions/hasMissingReviews_test.go
> +											Login: github.String("john"),
In the context of this test is not relevant the pull request author.

2022-07-29 16:52 UTC, ferreiratiago commented on plugins/aladino/functions/hasMissingReviews.go
> +	requestedTeams := e.GetPullRequest().RequestedTeams
Agreed.

2022-07-29 18:53 UTC, marcelosousa requested changes

2022-07-29 18:53 UTC, marcelosousa commented on plugins/aladino/functions/isWaitingForReview.go
> +	}
I think it is clearer if we move this code to the beginning of the func.

2022-07-29 18:53 UTC, marcelosousa commented on plugins/aladino/functions/isWaitingForReview.go
> +	// FIXME: Extract last update date from push instead of commit.
Please add a reference to the issue in the FIXME.

2022-07-29 18:53 UTC, marcelosousa commented on plugins/aladino/functions/isWaitingForReview.go
> +	lastUpdateDate := commits[len(commits)-1].Commit.Committer.Date
Edge case: protect against nil `Committer`

2022-07-29 18:53 UTC, marcelosousa commented on plugins/aladino/functions/isWaitingForReview.go
> +		}
As discussed, this is still not quite what we had in mind.

2022-08-01 09:59 UTC, marcelosousa requested changes

2022-08-01 09:59 UTC, marcelosousa commented on plugins/aladino/functions/isWaitingForReview.go
> +	author := e.GetPullRequest().GetUser().GetLogin()
Nitpick: we call `GetPullRequest` 6 times here. I think the code would be more readable if we used an auxiliary variable.

2022-08-01 09:59 UTC, marcelosousa commented on plugins/aladino/functions/isWaitingForReview.go
> +		if lastUserReview != nil && review.GetSubmittedAt().After(lastUserReview.GetSubmittedAt()) {
```suggestion
		lastUserReview, ok := lastReviewByUser[userLogin]
		if ok && review.GetSubmittedAt().After(lastUserReview.GetSubmittedAt()) {
```

2022-08-01 09:59 UTC, marcelosousa commented on plugins/aladino/functions/isWaitingForReview.go
> +		lastReviewByUser[userLogin] = review
It seems that we are doing the same action. Why is the conditional required? I must be missing something.

2022-08-01 11:02 UTC, marcelosousa approved these changes

2022-08-01 13:08 UTC, merged