feat!: store action built-ins messages by severity in environment
reviewpad/reviewpad pull request #219
Opened 2022-08-03 11:01 UTC by shay2025

## Description

This pull request a new parameter in the environment which consists of a storage to the action built-ins messages.
For now, we store the fatal messages which once catched, the program action stops and the GitHub action fails.

Further development involves propagating this parameter to store not only fatal messages but all messages returned by action built-ins (and maybe function built-ins), categorizing them by severity (fatal, error, warning, etc) and add them to the generated report.

## Related issue

Closes #187

## Type of change

Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How was this tested?

Used the pull request https://github.com/explore-dev/didactic-robot/pull/47 for testing.

1. Change the reviewpad.yml file in the https://github.com/explore-dev/didactic-robot locally
2. On the branch of the proposed changes executed the command:
`./main -dry-run=false -github-token=[GITHUB_TOKEN] -pull-request=https://github.com/explore-dev/didactic-robot/pull/47 -reviewpad=../didactic-robot/reviewpad.yml -event-payload=cmd/cli/resources/test_open_pr_event.json`

## Checklist

- [x] I have performed a self-review of my code
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask)

2022-08-04 20:02 UTC, ferreiratiago requested changes
As we discussed we should update the Interpreter `Report` function in order to report all messages reported from builtins. And also update the Interpreter `ExecProgram` to return the exit status.

2022-08-04 20:02 UTC, ferreiratiago commented on runner.go
> +		aladinoInterpreter.CheckForFatal()
No need for this.

2022-08-08 11:08 UTC, shay2025 commented
Before merging this pull request, upon approval, review https://github.com/reviewpad/action/pull/22

2022-08-08 14:03 UTC, ferreiratiago requested changes
We need to create a type `ExitStatus` to make it more verbose what's happening.

2022-08-08 14:03 UTC, ferreiratiago commented on engine/env.go
> +	ExecProgram(program *Program) (int, error)
I would suggest to create a type for the exit status.

```go
type ExitStatus int

const ExitStatusSuccess = 1
const ExitStatusFailure    = 0
```

2022-08-08 14:14 UTC, shay2025 commented on .github/workflows/build.yml
> +      - name: Convert coverage to lcovreb
Sorry this resulted of a previous rebase.

2022-08-08 14:17 UTC, shay2025 commented on engine/env.go
> +	ExecProgram(program *Program) (int, error)
Here I think you meant the opposite. The success exit status is 0 and the failure exit status is 1.

2022-08-08 15:16 UTC, ferreiratiago approved these changes

2022-08-09 09:37 UTC, merged