Fetch last update date from push for
reviewpad/reviewpad pull request #221
Opened 2022-08-03 15:18 UTC by pkbhowmick

Signed-off-by: Pulak Kanti Bhowmick <pkbhowmick007@gmail.com>

## Description

## Related issue

## Type of change

## How was this tested?

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or that my feature works 
- [ ] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask)

2022-08-04 14:47 UTC, ferreiratiago requested changes
Thanks for the contribution @pkbhowmick 🙌🏼 It's looking great. We need to update the graphql query to also cover the force push case. Please have a look at the comments. Thanks

2022-08-04 14:47 UTC, ferreiratiago commented on utils/github.go
> +}
This query does not cover all cases. It solves the problem of someone changing the commit date but it misses any force pushes. My suggestion is to query github timeline for `HEAD_REF_FORCE_PUSHED_EVENT` and `PULL_REQUEST_COMMIT`.

Here's the query for [graphiql](https://graphql-dotnet.github.io/docs/getting-started/graphiql/).
```graphql
{
  repository(owner: "ferreiratiago", name: "paddy") {
    pullRequest(number: 4) {
      timelineItems(last: 2, itemTypes: [HEAD_REF_FORCE_PUSHED_EVENT, PULL_REQUEST_COMMIT]) {
        nodes {
          ... on HeadRefForcePushedEvent {
            createdAt
          }
          ... on PullRequestCommit {
            commit {
              pushedDate
            }
          }
        }
      }
    }
  }
}
```

_(The query is prepared for a personal example project)_

WDYT?

2022-08-04 14:47 UTC, ferreiratiago commented on utils/github.go
> +type PRLastPushedDateQuery struct {
Suggestion name `LastPushedEventDateQuery`

2022-08-04 14:47 UTC, ferreiratiago commented on utils/github.go
> +func GetPRLastPushedCommitDate(ctx context.Context, client *githubv4.Client, owner string, repo string, number int) (time.Time, error) {
In order to maintain consistency let's call this `GetPullRequestLastPushedEventDate`.

2022-08-04 14:47 UTC, ferreiratiago commented on utils/github.go
> +	var pullRequestQuery PRLastPushedDateQuery
Naming suggestion `lastPushedEventDateQuery`.

2022-08-04 14:47 UTC, ferreiratiago commented on plugins/aladino/functions/isWaitingForReview.go
>  	}
I'm afraid this is not required anymore.

2022-08-04 17:36 UTC, pkbhowmick commented on utils/github.go
> +}
yes, I also think so.

2022-08-04 21:59 UTC, ferreiratiago requested changes
We are going into the right direction. Please have a look at the comments.

2022-08-04 21:59 UTC, ferreiratiago commented on utils/github.go
> +			} `graphql:"timelineItems(last: 2, itemTypes: [HEAD_REF_FORCE_PUSHED_EVENT, PULL_REQUEST_COMMIT])"`
No need for the last 2. My bad that suggested that. One is enough - the last one :)

2022-08-04 21:59 UTC, ferreiratiago commented on utils/github.go
> +type LastPushedEventDateQuery struct {
Now that we iterate again I was thinking if we shouldn't call this struct `LastPushQuery`. If we think about it `pushed` doesn't add more value, `event` is just a detail and `date` is one of the fields. We may even add more fields and having `date` in the name will mess that up. WDYT?

2022-08-04 21:59 UTC, ferreiratiago commented on utils/github.go
> +func GetPullRequestLastPushedEventDate(ctx context.Context, client *githubv4.Client, owner string, repo string, number int) (time.Time, error) {
I think we could rename this to `GetPullRequestLastPushDate`. Saying `PushedEvent` does not really helps to understand what the function does.

2022-08-04 21:59 UTC, ferreiratiago commented on utils/github.go
> +	varGQLastPushedEventDate := map[string]interface{}{
These get updated to `lastPushQuery` and `varGQLastPush`.

2022-08-04 21:59 UTC, ferreiratiago commented on utils/github.go
> +	}
Let's make more verbose here and also add some lines between.

```suggestion
	
	hasLastPush := len(lastPushQuery.Repository.PullRequest.TimelineItems.Nodes) > 0
	if  !hasLastPush {
		return time.Time{}, errors.New("last push not found")
	}
	
```

2022-08-04 21:59 UTC, ferreiratiago commented on utils/github.go
> +	return pushedEventDates[0], nil
I'm not sure if we need all this. Since we are fetching only one event, or even fetching multiple, we could extract the last one.

However, we need to make sure that the order is always the correct one, i.e. that the last event was in fact the last event to happen. Can you please check if that's the case? i.e. If github graphql API guarantees that the order is the correct one?

If that's the case I believe we can simplify this logic :)

2022-08-05 15:20 UTC, pkbhowmick commented on utils/github.go
> +	return pushedEventDates[0], nil
Can you please check if that's the case?
yes, I checked it. The github api returns the actual last event.

2022-08-08 09:51 UTC, ferreiratiago requested changes
Please use graphql `__typename` to choose which event to handle. Also, please remove the pull request from draft and update the title to follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

2022-08-08 09:51 UTC, ferreiratiago commented on utils/github.go
> +	}
We can use graphql `__typename` for this. Can you please have a look?

2022-08-28 17:51 UTC, marcelosousa commented
@ferreiratiago: bumping the priority in this pull request.

2022-09-08 10:20 UTC, ferreiratiago approved these changes
This pull request is to be continue on the following issues:
- #331 
- #332

2022-09-08 10:20 UTC, merged