feat: sprintf returns formated string
reviewpad/reviewpad pull request #225
Opened 2022-08-04 17:47 UTC by versoul

## Description

Feat adds formated string buit-in

## Related issue

Closes [issue #195](https://github.com/reviewpad/reviewpad/issues/195)

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?
Ran `task test` command.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
[x] Ask: this pull request requires a code review before merge

2022-08-10 09:05 UTC, marcelosousa requested changes

2022-08-10 09:05 UTC, marcelosousa commented on plugins/aladino/functions/sprintf.go
> +	}
In L14, it is specified that the type of `sprintf` is a string plus an array of strings. This means that it's not possible for a `val` to be a IntValue as the type checker will complain. For now, it's best to simplify and assume that we can only pass vals of type String.

2022-08-10 09:05 UTC, marcelosousa commented on plugins/aladino/functions/sprintf_test.go
> +	fmt.Println(gotString)
This seem like debug code.

2022-08-10 09:21 UTC, versoul commented on plugins/aladino/functions/sprintf.go
> +	}
it was for a future, but fixed

2022-08-10 09:21 UTC, versoul commented on plugins/aladino/functions/sprintf_test.go
> +	fmt.Println(gotString)
fixed

2022-08-11 13:10 UTC, marcelosousa approved these changes

2022-08-11 13:13 UTC, merged