fix: addToProject fetches the wrong project
reviewpad/reviewpad pull request #234
Opened 2022-08-05 14:23 UTC by versoul

## Description

Fixed issue when we get project with similar name

## Related issue

Closes [issue #222](https://github.com/reviewpad/reviewpad/issues/222)

## Type of change

Bug fix (non-breaking change which fixes an issue)

## How was this tested?

run tests

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
[x] Ask: this pull request requires a code review before merge

2022-08-12 08:56 UTC, ferreiratiago requested changes
Please have a look at the comments :)

2022-08-12 08:56 UTC, ferreiratiago commented on utils/github_projects.go
> +		if node.Title == name {
I would suggest to convert both `node.Title` and `name` to lowercase before comparing. This is to make sure that the comparison is not case-sensitive.

2022-08-12 08:56 UTC, ferreiratiago commented on utils/github_projects.go
> +	// with a partially matching name and then filter programmatically
```suggestion
	// We request the first 50 projects since GitHub can return several projects with a partially matching name.
    // For instance, a GitHub organization with the two projects "private project" and "public project",
    // a query for "private project" will return both projects. This is because both projects have the word "project".
```

2022-08-12 08:56 UTC, ferreiratiago commented on utils/github_projects.go
> +		if node.Title == name {
Also, we need to add a new unit test for this. If you run the unit tests form the package you will see not all code is cover by the current unit tests. A good unit test could be `TestGetProjectV2ByName_WhenSeveralProjectsFound`.

2022-08-12 08:56 UTC, ferreiratiago commented on plugins/aladino/actions/addToProject_test.go
> +			name:                                  "when 2 projects with similar names",
This test shouldn't be here. This test should be performed on the unit tests of `GetProjectV2ByName`.

2022-08-12 10:05 UTC, versoul commented
@ferreiratiago fixed

2022-08-12 11:13 UTC, ferreiratiago requested changes

2022-08-12 11:13 UTC, ferreiratiago commented on lang/aladino/parser.go
> +var AladinoExca = [...]int8{
Why is this file here?

2022-08-12 11:13 UTC, ferreiratiago commented on codehost/github/projects_test.go
> +	assert.Equal(t, nil, err)
```suggestion
	assert.Nil(t, err)
```

2022-08-12 11:13 UTC, ferreiratiago commented on codehost/github/projects.go
> +		if strings.ToLower(node.Title) == strings.ToLower(name) {
Please use `strings.EqualFold` https://pkg.go.dev/strings#EqualFold

2022-08-12 11:13 UTC, ferreiratiago commented on codehost/github/projects_test.go
> +	assert.NotNil(t, project)
This does not test what we want. Just makes sure the output value is not null regardless of being correct or wrong.

We need to make sure that the right project is selected.

2022-08-12 11:26 UTC, versoul commented
@ferreiratiago done, actually i don't know, my IDE always add changes like int[] -> int8[] to generated file parser.go every time when i open this file? is it nor good? may be it is because i use mac?

2022-08-16 08:26 UTC, ferreiratiago requested changes

2022-08-16 08:26 UTC, ferreiratiago commented on codehost/github/projects_test.go
> +}
The test can be improved a bit more. The way it is if I change the value of `mockProjectName` the graphql query will fail. We don't want that. We want it to return an empty value but not to fail.

```suggestion
func TestGetProjectV2ByName_WhenSeveralProjectsFound(t *testing.T) {
	mockProjectName := "reviewpad2"
	mockedGetProjectByNameQuery := fmt.Sprintf(
		`{
            "query": "query($name:String! $repositoryName:String! $repositoryOwner:String!) {
                repository(owner: $repositoryOwner, name: $repositoryName) {
                    projectsV2(query: $name, first: 50, orderBy: {field: TITLE, direction: ASC}) {
                        nodes{id,number,title}
                    }
                }
            }",
            "variables": {
                "name": "%v",
                "repositoryName":"default-mock-repo",
                "repositoryOwner":"john"
            }
        }`,
		mockProjectName,
	)
	mockedGetProjectByNameQueryBody := `{
        "data": {
            "repository":{
                "projectsV2":{
                    "nodes":[
                        {
                            "id": "2",
                            "number": 2,
                            "title": "1eviewpad"
                        },
                        {
                            "id": "1",
                            "number": 1,
                            "title": "reviewpad"
                        }
                    ]
                }
            }
        }
    }`
	mockedEnv := aladino.MockDefaultEnv(
		t,
		[]mock.MockBackendOption{},
		func(res http.ResponseWriter, req *http.Request) {
			query := utils.MinifyQuery(aladino.MustRead(req.Body))
			switch query {
			case utils.MinifyQuery(mockedGetProjectByNameQuery):
				aladino.MustWrite(
					res,
					mockedGetProjectByNameQueryBody,
				)
			}
		},
		aladino.MockBuiltIns(),
		nil,
	)
	mockOwner := host.GetPullRequestBaseOwnerName(mockedEnv.GetPullRequest())
	mockRepo := host.GetPullRequestBaseRepoName(mockedEnv.GetPullRequest())

	project, err := mockedEnv.GetGithubClient().GetProjectV2ByName(mockedEnv.GetCtx(), mockOwner, mockRepo, mockProjectName)

	assert.Nil(t, err)
	assert.NotNil(t, project)
	assert.Equal(t, mockProjectName, project.Title)
}
```

2022-08-16 08:26 UTC, ferreiratiago commented on lang/aladino/parser.go
>  var base int
Please remove this file from the pull request.

You can run the git command `git checkout main lang/aladino/parser.go` and add the file.

2022-08-16 09:26 UTC, versoul commented
@ferreiratiago done

2022-08-16 09:37 UTC, ferreiratiago approved these changes

2022-08-16 09:37 UTC, merged