Allow a comment only once in a pull request
reviewpad/reviewpad pull request #24
Opened 2022-06-22 10:35 UTC by ferreiratiago

- Add $commentOnce() action
- Add tests folder and mocks
- Add unit tests for $commentOnce() action
- Change access to commentOnce code
- Change access to commentOnce code in TestCommentOnceOnListCommentsFail
- Remove unnecessary whitespace
- Remove double copyright notice
- Add new lines to the end of files
- Add reviewpad comment annotation to comment body in commentOnce() action
- Change licence in aladino mocks and actions
- Update go.mod
- Change pointers in actions tests
- Paginate the list comments request in aladino actions
- Restore parser.go file from main
- Fix reviewpad comment annotation in commentOnce() unit tests
- Fix reviewpad comment annotation in commentOnce() action
- Improve commentOnce unit tests and github mocks

2022-06-22 14:04 UTC, shay2025 commented on plugins/aladino/actions.go
> +	commentBodyWithReviewpadAnnotation := fmt.Sprintf("\n%v\n%v", aladino.ReviewpadCommentAnnotation, commentBody)
A strange behaviour was happening when we only had `"%v%v"`.
For some reason, when we had this, although the create issue comment request was giving a successful status code, the comment didn't appear in the github interface.
However, when it was added the `\n` at the beginning, before the reviewpad annotation, the comment now appeared in the interface.

2022-06-22 15:16 UTC, shay2025 commented on plugins/aladino/actions.go
> +	commentBodyWithReviewpadAnnotation := fmt.Sprintf("\n%v\n%v", aladino.ReviewpadCommentAnnotation, commentBody)
This was happening because the following was occuring:
1. A comment starting with "<!--@annotation-reviewpad-->" was made.
2. When the action runs, we generate a new report
3. Before generating this new report, we find the old one and delete it (the functions `FindReportComment` and `DeleteReportComment` are executed in this order).
4. In the `FindReportComment` function, to find the report we were only using the regex `^<!--@annotation-reviewpad-->` when this regex not only finds the reports but also other comments made by reviewpad.
5. So once a comment with this condition was found it would be deleted right away and this was causing the non-appearance of the comment in the github interface since right after being created it was deleted.
6. To fix this, we specified even more the regex for the reviewpad report: `^<!--@annotation-reviewpad-->\\*\\*Reviewpad Report\\*\\*\n\n`. 
https://github.com/reviewpad/reviewpad/blob/908b598a366125e9b3b9c5dc033957df4dd55f5b/lang/aladino/report.go#L190-L192

2022-06-23 08:47 UTC, marcelosousa requested changes
Please see the comment on the annotations. We are almost there 🚀

2022-06-23 10:38 UTC, marcelosousa requested changes

2022-06-23 10:38 UTC, marcelosousa commented on plugins/aladino/actions.go
> +const ReviewpadCommentAnnotation = "<!--@annotation-reviewpad-->"
```suggestion
const ReviewpadCommentAnnotation = "<!--@annotation-reviewpad-single-comment-->"
```

2022-06-23 10:52 UTC, marcelosousa approved these changes
Looks good! 👍

2022-06-23 10:52 UTC, merged