Paginate list comments request in aladino report
reviewpad/reviewpad pull request #25
Opened 2022-06-23 12:00 UTC by shay2025

This pull request includes the following changes:
- Paginate list comments request made in `FindReportComment` function present in `lang/aladino/report.go`
- Added the `opts` argument in `GetPullRequestComments` function present in `utils/github.go`. This was added because when we want to make a request to list the comments of pull request we may want to add a set of options for this listing and this options may vary according to the context of the `GetPullRequestComments` function call. For example, the call made in `FindReportComment` in `lang/aladino/report.go` and the call made in `plugins/aladino/actions.go` differ.

Closes #9

2022-06-27 10:07 UTC, marcelosousa requested changes
Please check the comment - thank you!

2022-06-27 10:07 UTC, marcelosousa commented on plugins/aladino/actions.go
> +	comments, err := utils.GetPullRequestComments(e.GetCtx(), e.GetClient(), owner, repo, prNum, &github.IssueListCommentsOptions{})
We need to add a unit test to ensure that this argument does not have unintended consequences.

2022-06-27 11:17 UTC, shay2025 commented on plugins/aladino/actions.go
> +	comments, err := utils.GetPullRequestComments(e.GetCtx(), e.GetClient(), owner, repo, prNum, &github.IssueListCommentsOptions{})
We can't test the effect of this specific argument with unit tests.
To do a unit test we need to mock a response.
Whatever the parameters we put in this `github.IssueListCommentsOptions{}` the response will always be the same since the operations applied to the list of comments (sort, etc) are done by github and so since we are mocking the response, this will always be the same showing that the supposed operations won't have any effect.

2022-06-28 08:28 UTC, ferreiratiago approved these changes
LGTM

2022-06-29 14:13 UTC, marcelosousa approved these changes

2022-06-29 14:15 UTC, merged