feat: lambda function
reviewpad/reviewpad pull request #254
Opened 2022-08-10 17:57 UTC by versoul

## Description

Add Lambda functions support

## Related issue

Closes [issue #236](https://github.com/reviewpad/reviewpad/issues/236)

## Type of change

 New feature (non-breaking change which adds functionality) 

## How was this tested?

run tests

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
[x] Ask: this pull request requires a code review before merge

2022-08-22 15:01 UTC, marcelosousa requested changes
Thanks 🙌 ! Please check the comment.

2022-08-22 15:01 UTC, marcelosousa commented on lang/aladino/parse_test.go
> +		},
@versoul: I have added more unit tests to check the feature and this one is failing.

2022-08-22 17:42 UTC, versoul commented
@marcelosousa is it a good fix? i think you miss comma, because all our functions looks the same
$changed("@1.go", "@1.md")
and javascript arrow functions looks the same
let myFunction = (a, b) => a * b;

What do you think?

2022-08-28 17:44 UTC, marcelosousa approved these changes

2022-08-28 17:44 UTC, merged