feat: add patterns to size built-in
reviewpad/reviewpad pull request #269
Opened 2022-08-20 12:00 UTC by versoul

## Description

Adds patterns to Size built-in

## Related issue

Closes [issue #89](https://github.com/reviewpad/reviewpad/issues/268)

## Type of change

Breaking change (fix or feature that would cause existing functionality to not work as expected)

!!! now all Size built-in expects empty arrays as pattern, it wouldn't work without params as earlier

## How was this tested?

run tests and try to run reviewpad as a CLI with new config

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-08-22 09:19 UTC, marcelosousa requested changes
Thanks for this contribution @versoul! 🙌  

This solution is not backwards compatible - all users that were previously using `$size()` will now have to update to something like `$size(".*")`. 

We need to do something similar to what we did with the `$merge()` action - check the transform.go file.

2022-08-22 17:21 UTC, versoul commented
@marcelosousa fixed

2022-08-26 15:30 UTC, marcelosousa requested changes
This feature is still not working as intended. Please check the comment. As I mentioned before, we'll need to change the file transform.go so that if $size does not have arguments, it will add the empty array as an argument.

2022-08-26 15:30 UTC, marcelosousa commented on lang/aladino/parser.go
> -var AladinoExca = [...]int{
It is strange that this file was modified - there should be no changes in this file for this feature :(

2022-08-26 15:30 UTC, marcelosousa commented on plugins/aladino/functions/size.go
> +	}
This conditional is dead code because in L17 it is specified that size always receives at least one argument.

2022-08-30 12:44 UTC, versoul commented on lang/aladino/parser.go
> -var AladinoExca = [...]int{
i think this file changed every time when i run tests...

2022-08-30 12:58 UTC, versoul commented on plugins/aladino/functions/size.go
> +	}
this condition for case when we pass empty array as exclude param $size([]) and it works and needed, i rechecked again with this line and without

2022-08-30 12:59 UTC, versoul commented
@marcelosousa done

2022-09-06 08:31 UTC, marcelosousa approved these changes

2022-09-06 08:40 UTC, merged