Request the review of a set of teams
reviewpad/reviewpad pull request #27
Opened 2022-06-27 09:04 UTC by shay2025

This pull request introduces a new action called $assignTeamReviewer() that requests the review of a given set of team slugs.

It was also added unit tests for this action.

Documentation: https://github.com/reviewpad/docs/pull/3

Closes #26.

2022-06-27 10:18 UTC, marcelosousa requested changes
Thanks 👍 I left some comments in the code!

2022-06-27 10:18 UTC, marcelosousa commented on plugins/aladino/actions.go
> +		if !team.HasKindOf(aladino.STRING_VALUE) {
This is not necessary as in the type declaration we already specify that it is an array of strings.

2022-06-27 10:18 UTC, marcelosousa commented on plugins/aladino/actions.go
> +	teamReviewersSlugs := []string{}
Use `make([]string, ...)`

2022-06-27 10:18 UTC, marcelosousa commented on plugins/aladino/actions.go
> +	teamReviewers := arg.(*aladino.ArrayValue).Vals
Please check that `len(teamReviewers) > 0` and return error otherwise

2022-06-27 10:18 UTC, marcelosousa commented on plugins/aladino/actions.go
> +	}
This is not necessary as in the type declaration we already declare that this built-in must have one argument.

2022-06-27 10:18 UTC, marcelosousa commented on plugins/aladino/actions.go
> +	repo := utils.GetPullRequestRepoName(e.GetPullRequest())
Nitpick: I think it is more readable if we assign `e.GetPullRequest()` to an auxiliary variable.

2022-06-27 10:18 UTC, marcelosousa commented on plugins/aladino/actions_test.go
> +}
I think these tests are not necessary because before running built-ins we pass the type checker which will validate these. However, we need to add a unit test that we don't pass an empty array of strings.

2022-06-27 10:18 UTC, marcelosousa commented on plugins/aladino/actions_test.go
> +	assert.Equal(t, teamsToRequestForReview, requestedTeamReviewers)
As standard in Go, lets keep the naming of the variables in these tests starting with `want` and `got`. Please rename `teamsToRequestForReview` to `wantTeamReviewers` and `requestedTeamReviewers` to `gotTeamReviewers`.

2022-06-27 14:48 UTC, shay2025 commented on plugins/aladino/actions.go
> +		if !team.HasKindOf(aladino.STRING_VALUE) {
If so, then we don't need this:
https://github.com/reviewpad/reviewpad/blob/1e99e64910bb6d8a7fb3e7eb70683b17e8de6d23/plugins/aladino/actions.go#L128-L130

2022-06-27 16:48 UTC, marcelosousa commented on plugins/aladino/actions.go
> +		if !team.HasKindOf(aladino.STRING_VALUE) {
That's true. We can do that fix in another pull request :)

2022-06-27 16:51 UTC, marcelosousa approved these changes
Just a small comment in the naming of the test functions. Otherwise seems solid - thanks! 🚀

2022-06-27 16:51 UTC, marcelosousa commented on plugins/aladino/actions_test.go
> +func TestAssignTeamReviewers_WhenNoTeamSlugsAreProvided(t *testing.T) {
Since the built-in name is `assignTeamReviewer` shouldn't these tests be called `TestAssignTeamReviewer_XXX`? There's an extra `s` in `Reviewer`.

2022-06-28 08:37 UTC, ferreiratiago approved these changes
Just a minor comment.

2022-06-28 08:37 UTC, ferreiratiago commented on plugins/aladino/actions_test.go
> +	wantTeamReviewers := []string{
I will suggest to add `teamA` and `teamB` as variable, i.e.

 ```go
teamA := "core"
teamB := "reviewpad-project"
wantTeamReviewers := []string{teamA, teamB}
```

2022-06-28 08:42 UTC, ferreiratiago commented
Can we add the related `reviewpad/docs` pull request in the pull request description?

2022-06-28 08:59 UTC, marcelosousa approved these changes

2022-06-29 14:07 UTC, merged