feat: add stale pull requests specification
reviewpad/reviewpad pull request #283
Opened 2022-08-23 15:49 UTC by shay2025

## Description

This pull request introduces the specification for stale pull requests.

## Related issue

Closes #241 

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?

It was done 2 tests.
1. Ran `task check -f` cmd.
2. Opened a PR on the testing repo and ran the `reviewpad-cli` command on the branch of the PR: `./reviewpad-cli run -p [PULL_REQUEST] -t [GITHUB_TOKEN] -e [EVENT_PAYLOAD] -f [REVIEWPAD_FILE]` where the reviewpad file used the `$lastEventAt` built-in with easily tested timestamps.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-08-23 16:17 UTC, shay2025 commented
TODO: After the acceptance of this pull request, an issue should be opened asking for the feature of automatic stale label removal upon recent activity on a stale pull request.

2022-08-24 11:31 UTC, marcelosousa requested changes

2022-08-24 11:31 UTC, marcelosousa commented on stale_pr.yml
> +      - '$close()'
```suggestion
      - '$close("Closing because this pull request has been inactive for one month.")'
```

2022-08-24 11:31 UTC, marcelosousa commented on .github/workflows/pull_request_stale.yml
> +name: Close Stale Pull Requests
```suggestion
name: Close Stale Pull Requests and Issues
```

2022-08-24 11:31 UTC, marcelosousa commented on .github/workflows/pull_request_stale.yml
> +    if: ${{ github.event.actor != 'reviewpad-bot' }}
```suggestion
```

2022-08-24 11:31 UTC, marcelosousa commented on stale_pr.yml
> +edition: professional
```suggestion
```

2022-08-24 11:31 UTC, marcelosousa commented on stale_pr.yml
> +  - name: check-stale-pr
```suggestion
  - name: check-stale-pr
     on:
        - "issue"
        - "pull_request"
```

2022-08-24 11:31 UTC, marcelosousa commented on stale_pr.yml
> +    spec: '$rule("labeled-as-stale-pr") && $lastEventAt() < 7 days ago'
inline these two rules

2022-08-24 11:31 UTC, marcelosousa commented on stale_pr.yml
> +  stale-pr-label:
do not make it specific to pull request.

2022-08-24 11:31 UTC, marcelosousa commented on stale_pr.yml
> +      - '$close()'
I think we can combine the workflows into one.

2022-08-24 18:05 UTC, marcelosousa approved these changes

2022-08-24 18:06 UTC, merged