Feat/assign reviewer with logic
reviewpad/reviewpad pull request #295
Opened 2022-08-24 07:12 UTC by versoul

## Description

Adds new built-in assignReviewerWithPolicy

## Related issue

Closes [issue #164](https://github.com/reviewpad/reviewpad/issues/164)

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?

Run in test config & enviropment
run tests

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-08-28 18:28 UTC, marcelosousa requested changes
Please rebase with the latest and remove dependencies of old host-event-handler package.

2022-08-28 18:28 UTC, marcelosousa commented on go.mod
> +	github.com/reviewpad/host-event-handler v0.0.3
This package should not be used anymore.

2022-08-30 12:41 UTC, versoul commented
@marcelosousa done

2022-10-06 15:45 UTC, ferreiratiago commented
Closing in favor of https://github.com/reviewpad/reviewpad/pull/382

2022-10-06 15:45 UTC, closed without merging