test: improve PaginatedRequest and ParseLink tests
reviewpad/reviewpad pull request #301
Opened 2022-08-24 13:32 UTC by shay2025

## Description

This pull request introduces the improvement of PaginatedRequest and ParseLink related tests in order to adopt the TDT format; another improvement made was the adoption of `mock.WithRequestMatchPages` in order to mock paginated requests.
Besides this, it was removed the unit tests for getters since there is no logic to be tested there.

## Related issue

*None*

## Type of change

Improvements (non-breaking change without functionality)

## How was this tested?

Ran `task check -f` cmd.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-08-26 15:46 UTC, marcelosousa requested changes
Thanks for this PR 🙌  I've left a comment in the diff - I don't see any changes about ParseLink - maybe you can leave a comment in the code about that?

2022-08-26 15:46 UTC, marcelosousa commented on codehost/github/pull_requests_test.go
> +		},
Please add a unit test so that we can test when the request for the second page fails. This way we will be able to reach https://github.com/reviewpad/reviewpad/blob/main/codehost/github/pagination.go#L31

2022-08-29 14:47 UTC, shay2025 commented on codehost/github/pull_requests_test.go
> +		},
@marcelosousa the parse link improvements are related with `parseNumPagesFromLink` function where the previous existing tests were converted to TDT which are contained in `TestParseNumPagesFromLink` in this PR.

2022-08-31 10:38 UTC, marcelosousa approved these changes

2022-08-31 10:41 UTC, merged