feat: close issue/pull request with comment
reviewpad/reviewpad pull request #315
Opened 2022-08-26 09:09 UTC by shay2025

## Description

This pull request introduces an improvement `$close()` by adding the possibility of closing an issue/pull request with a comment.

## Related issue

Closes #296

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?

Ran `task check -f` cmd and used the `reviewpad-cli run` cmd against a testing repo with `reviewpad.yml` where a triggered rule had the `$close()` action.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-08-26 09:14 UTC, shay2025 commented
This https://github.com/reviewpad/docs/pull/20 needs to be merged before this PR is.

2022-08-26 15:53 UTC, marcelosousa requested changes

2022-08-26 15:53 UTC, marcelosousa commented on codehost/github/target/issue_target.go
> +	if comment != "" {
I think it makes more sense for this validation to happen the `t.Comment` function.

2022-08-26 15:53 UTC, marcelosousa commented on codehost/github/target/issue_target.go
> +	if comment != "" {
It would actually be great to document in the Comment function what happens if the comment the empty string.

2022-08-26 15:53 UTC, marcelosousa commented on plugins/aladino/actions/close.go
> +	return t.Close(comment)
```suggestion
	return e.GetTarget().Close(comment)
```

2022-08-26 15:53 UTC, marcelosousa commented on plugins/aladino/actions/close_test.go
> +			commentCreated = false
I don't think this is thread safe because if we run the tests in parallel we might get data races. Need to find another way to get the state :-)

2022-08-26 16:24 UTC, shay2025 commented on codehost/github/target/issue_target.go
> +	if comment != "" {
Idk if that would be desirable because whenever we comment `""` this action would be ignored, following your suggestion.
But, for now, we only want this to happen in the particular case of `Close()` in other cases we may want to throw an error on  other comments like `""` like the already defined default behavior. For example, `$comment("")` should return an error, should not?

2022-08-26 16:30 UTC, shay2025 commented on plugins/aladino/actions/close_test.go
> +			commentCreated = false
I don't think the tests will be run in parallel.
Tests inside one `_test.go` file do not run in parallel by default - to enable parallel execution we would have to call `t.Parallel()` in the test case.

2022-08-26 17:19 UTC, marcelosousa commented on codehost/github/target/issue_target.go
> +	if comment != "" {
I think we need to check what exactly happens if a user tries $comment(""). I don't think it should return an error in that case.

2022-08-26 23:52 UTC, shay2025 commented on codehost/github/target/issue_target.go
> +	if comment != "" {
I took the decision of implementing that way because github throws an error saying that a comment can't have an empty body

2022-08-31 13:19 UTC, shay2025 commented on codehost/github/target/issue_target.go
> +	if comment != "" {
@marcelosousa I tried executing `$comment("")` in the PR https://github.com/explore-dev/didactic-robot/pull/68 and as expected a fail happens.
Log message: `Error: error running reviewpad team edition. Details POST https://api.github.com/repos/explore-dev/didactic-robot/issues/68/comments: 422 Validation Failed [{Resource:IssueComment Field:data Code:unprocessable Message:Body cannot be blank}]`

2022-08-31 13:23 UTC, shay2025 commented on codehost/github/target/issue_target.go
> +	if comment != "" {
I still believe `t.Comment()` should remain unchanged since this function has a direct purpose: create a comment.
If it doesn't have the conditions to do so (e.g., empty comment) it should fail - a comment CANNOT have a blank comment or else it fails to be a comment.
Said that, the validation you mentioned on the first comment of this thread, only makes sense to be made in `t.Close()` since this function can have two behaviours:
1. Perform a close WITH comment
2. Perform a close WITHOUT comment
It is a particular case.

2022-09-06 08:43 UTC, marcelosousa approved these changes

2022-09-06 08:47 UTC, merged