feat: Allow number sign in label color hex values
reviewpad/reviewpad pull request #341
Opened 2022-09-02 12:09 UTC by fredoliveira

## Description

When describing label colors while editing the Reviewpad configuration file, it is often useful to visualize the colors in place without having to copy the hex values somewhere else. The current [Reviewpad specification](https://docs.reviewpad.com/guides/syntax#label) for labels requires hex values defined in the configuration to _not_ include the number sign. That means mechanisms that detect hex color values will not match. Like so:

Very uncool:

![Screenshot 2022-09-02 at 12 40 24](https://user-images.githubusercontent.com/4189/188132033-47484d9c-878a-45b8-bc05-983325a9b4c0.png)

Isn't this a lot better:

![Screenshot 2022-09-02 at 12 41 01](https://user-images.githubusercontent.com/4189/188132082-6422d923-ae4d-4a7c-88f3-42d98129de11.png)

This changeset makes the number sign optional, by doing 2 main things:

- The regex that matches and validates colors now allows for an optional `#` (e.g: `#abcdef` is now valid)
- Before we [push the label to Github](https://docs.github.com/en/rest/issues/labels#create-a-label), we trim the `#` if it exists [^1]

## Related issue

Closes #340 

## Type of change

Improvements (non-breaking change without functionality)

## How was this tested?

My Go chops aren't formidable, but I assume I didn't completely botch it (yet) 😂 

```
❯ task test
task: [test] gotestsum -- -coverprofile=coverage.out ./...
∅  .
∅  cli
∅  cli/cmd
✓  codehost (473ms) (coverage: 73.5% of statements)
✓  utils (169ms) (coverage: 39.1% of statements)
✓  handler (243ms) (coverage: 94.6% of statements)
✓  lang/aladino (445ms) (coverage: 84.5% of statements)
✓  utils/fmtio (523ms) (coverage: 100.0% of statements)
✓  utils/report (601ms) (coverage: 100.0% of statements)
✓  engine (857ms) (coverage: 73.1% of statements)
✓  plugins/aladino/actions (496ms) (coverage: 89.0% of statements)
✓  plugins/aladino/functions (274ms) (coverage: 97.8% of statements)
✓  codehost/github (1.458s) (coverage: 62.5% of statements)
∅  codehost/github/target
∅  collector
∅  engine/testutils
∅  plugins/aladino
∅  plugins/aladino/services

DONE 685 tests in 4.909s
task: [test] . scripts/exclude-from-code-coverage.sh
```

## Checklist

- [x] I have performed a self-review of my code
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

- [x] Ask: this pull request requires a code review before merge

[^1]: Why is everybody hating on the number sign `#`? We're taking a stand here.

2022-09-02 19:05 UTC, marcelosousa requested changes
Many thanks for this contribution 🙌 
I just made a small suggestion. I'm working on adding a unit tests to your branch - I think I should get permissions to do it!

2022-09-02 19:05 UTC, marcelosousa commented on engine/labels.go
> +
We can use the `TrimPrefix` that will remove the "#" if it exists, otherwise it remains unchanged. 

```suggestion
		label.Color = strings.TrimPrefix(label.Color, "#")
```

2022-09-02 19:52 UTC, fredoliveira commented on engine/labels.go
> +
Oh, this is what I get for only having very rough knowledge of the Go standard library. Had no idea `TrimPrefix` existed. Committing that change! 🙌🏼

2022-09-03 12:27 UTC, marcelosousa approved these changes
Thanks again for this contribution 🙌

2022-09-03 12:29 UTC, merged

2022-09-04 16:27 UTC, fredoliveira commented
@marcelosousa happy to help 🙌🏼 🤝