Substitute PR request for PR requested reviewers request in $assignRandomReviewer action builtin
reviewpad/reviewpad pull request #35
Opened 2022-06-30 15:52 UTC by shay2025

This pull request introduces the replacement of the get pull request request in `$assignRandomReviewer` action builtin that is used to get the requested reviewers when we can specify the request to get the requested reviewers directly.

Closes #34.

2022-07-04 09:53 UTC, shay2025 commented
@marcelosousa after a user makes an approval to a pull request they won't be taken into account in the ListReviewers response. So right now that means that with `$assignRandomReviewer` exists the possibility that it can be re-requested a review.

2022-07-04 16:08 UTC, ferreiratiago requested changes
Some rename required. Please have a look.

[reviewpad-sig]: <>
[View on **Reviewpad**](https://beta.reviewpad.com/review/github.com/reviewpad/reviewpad/pull/35?codereviewid=ecdf30dd-14f3-4b57-94b0-1031a40efae9)

2022-07-04 16:08 UTC, ferreiratiago commented on utils/github.go
> +			fs, resp, err := client.PullRequests.ListReviewers(ctx, owner, repo, number, &github.ListOptions{
Please rename `fs` to `reviewers`.

2022-07-04 16:08 UTC, ferreiratiago commented on utils/github.go
> +	fs, err := PaginatedRequest(
Please rename `fs` to `reviewers`.

2022-07-05 15:17 UTC, ferreiratiago approved these changes
LGTM

2022-07-05 16:03 UTC, merged