feat: set conditions for a review to be done with review built-in
reviewpad/reviewpad pull request #404
Opened 2022-10-17 09:49 UTC by shay2025

## Description

The `$review` built-in seemed to have some flaws being one of them the fact that it performed a review whenever the action ran independently if the pull request had updates or not and if the last review was an `APPROVED`.
This built-in adds the condition that a review can only be performed if the pull request has updates since the last review made by `reviewpad-bot` and if the last review by that user is not an `APPROVED`.

## Related issue

Closes #398 

## Type of change

Improvements (non-breaking change without functionality)

## How was this tested?

Ran `task check -f` cmd.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-10-19 10:53 UTC, ferreiratiago approved these changes
Some minor suggestions. Please have a look.

2022-10-19 10:53 UTC, ferreiratiago commented on plugins/aladino/actions/review.go
> +	}
Why did we move this out of function? IMO, it was easier to understand with the function call `checkReviewBody`. WDYT?

2022-10-19 10:53 UTC, ferreiratiago commented on plugins/aladino/actions/review.go
> +	// since last review made by reviewpad-bot, then do nothing.
No need for this comment.

2022-10-19 10:53 UTC, ferreiratiago commented on plugins/aladino/actions/review.go
> +		if !lastReview.SubmittedAt.Before(t.PullRequest.GetUpdatedAt()) {
```suggestion
		if lastReview.SubmittedAt.After(t.PullRequest.GetUpdatedAt()) {
```

Replace `! Before` with `After` for better reading.

2022-10-19 10:59 UTC, ferreiratiago requested changes
Unfortunately this feature does not work as intended. It only works with reviewpad projects. Anyone outside of reviewpad won't be able to use it properly.

2022-10-19 10:59 UTC, ferreiratiago commented on plugins/aladino/actions/review.go
> +	reviewpadBot := "reviewpad-bot"
Totally miss this. This is not ok. `reviewpad-bot` is a bot from reviewpad. Anyone else using this `review` built-in will either have `github-actions` or any other user. This needs to be rethink, otherwise it only works for reviewpad.

We need to check if the current user running reviewpad (github actions or any other) has done any review, and not `reviewpad-bot`.

2022-10-19 12:52 UTC, shay2025 commented on plugins/aladino/actions/review.go
> +	reviewpadBot := "reviewpad-bot"
Should we use the workflow run actor?

2022-10-19 12:53 UTC, shay2025 commented on plugins/aladino/actions/review.go
> +	reviewpadBot := "reviewpad-bot"
I have commited a change that follows that approach.

2022-10-20 09:45 UTC, ferreiratiago requested changes

2022-10-20 09:45 UTC, ferreiratiago commented on plugins/aladino/actions/review.go
> +	reviewer := e.GetGithubActionActor()
IMO we need to rename this variable to `actionActorLogin`. Being a `reviewer` is just a detail.

2022-10-20 09:45 UTC, ferreiratiago commented on plugins/aladino/actions/review.go
> +		log.Printf("%+v", t.PullRequest.GetUpdatedAt())
If we are keeping this log we need to make clear what it is. The way it is we will see a date but is not clear that is that is about.

```suggestion
		log.Printf("Pull request updated at: %+v", t.PullRequest.GetUpdatedAt())
```

2022-10-27 08:39 UTC, ferreiratiago approved these changes
Minor suggestions.

2022-10-27 08:39 UTC, ferreiratiago commented on plugins/aladino/actions/review.go
> +	botAccount, _, err := e.GetGithubClient().GetClientREST().Users.Get(e.GetCtx(), "")
Why the name `botAccount`? This request provides the `authenticatedUser`

2022-10-27 08:39 UTC, ferreiratiago commented on plugins/aladino/actions/review.go
> +	botLogin := botAccount.GetLogin()
```suggestion
	authenticatedUserLogin := authenticatedUser.GetLogin()
```

2022-10-27 08:48 UTC, shay2025 commented on plugins/aladino/actions/review.go
> +	botAccount, _, err := e.GetGithubClient().GetClientREST().Users.Get(e.GetCtx(), "")
Because the objective is to get the bot account because it is the authenticated user.

2022-10-27 08:54 UTC, merged