feat: delete head branch built in action
reviewpad/reviewpad pull request #405
Opened 2022-10-17 13:01 UTC by zolamk

## Description

This PR adds a new builtin action `$deleteHeadBranch()`

## Related issue

Closes #385 

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?

Manual and unit tests.

## Checklist

- [X] I have performed a self-review of my code
- [X] I have added tests that prove my fix is effective or that my feature works 
- [X] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [X] Ask: this pull request requires a code review before merge

2022-10-17 14:54 UTC, shay2025 commented
@zolamk I believe this action should only happen if and when the pull request is closed or merged. Otherwise, when the actions runs it just closes the pull requets and deletes the head branch. Could you add those conditions to the implementation, please? Thanks!

2022-10-17 16:12 UTC, zolamk commented
> @zolamk I believe this action should only happen if and when the pull request is closed or merged. Otherwise, when the actions runs it just closes the pull requets and deletes the head branch. Could you add those conditions to the implementation, please? Thanks!

I've updated the PR, but maybe we could also have built-in functions such as `$merged()` and `$closed()` we can use in a rule like this
```
workflows:
  - name: delete-closed-pr-head
    description: Delete Closed PR Head
    always-run: true
    if:
      - rule: '$closed() || $merged()'
        extra-actions:
          - "$deleteHeadBranch()"
```

2022-10-17 20:51 UTC, marcelosousa commented
@zolamk @shay2025 we need to investigate why the `Ask` label is not being added here.

2022-10-18 11:35 UTC, zolamk commented
> @zolamk @shay2025 we need to investigate why the `Ask` label is not being added here.

@marcelosousa I think that probably happened because I used a capital `X` to mark the ask option when creating the PR, in the reviewpad file for this repo uses a small letter `x` to check for the ask mode here https://github.com/reviewpad/reviewpad/blob/c9152a079bd2c8d5c0949e43fe19ab0e602d278b/reviewpad.yml#L94
perhaps it can be changed like `spec: '$contains($description(), "[x] Ask:") || $contains($description(), "[X] Ask:")'` or a case-insensitive version of `$contains` built-in function can be added

2022-10-18 12:35 UTC, shay2025 requested changes
Just some minor changes

2022-10-18 12:35 UTC, shay2025 commented on plugins/aladino/actions/deleteHeadBranch.go
> +		return errors.New("pull request should be merged or closed before deleting head branch")
Let's just return `nil` instead of an error.
This is because if the action runs in all pull requests if it comes across closed/merged ones the action will fail and it shouldn't happen.

2022-10-18 12:35 UTC, shay2025 commented on plugins/aladino/actions/deleteHeadBranch_test.go
> +func TestDeleteHeadBranch_WhenPRIsNotMergedOrClosed(t *testing.T) {
Here you are testing the case scenario where the pull request is not merged AND closed.
We should do the following tests:
- when the pull request is closed but not merged;
- when the pull request is merged and closed (a merged pull request implies that it is closed but the other way around does not apply).

2022-10-18 12:35 UTC, shay2025 commented on plugins/aladino/actions/deleteHeadBranch_test.go
> +				http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
In order to check if the request to delete the head branch was performed, we could add a flag that indicated if the request was performed.
```suggestion
func TestDeleteHeadBranch_SuccessMerged(t *testing.T) {
    var isDeleteHeadBranchRequestPerformed bool
	mockedPullRequest := aladino.GetDefaultMockPullRequestDetailsWith(&github.PullRequest{
		Merged:   github.Bool(true),
		ClosedAt: nil,
	})
	mockedEnv := aladino.MockDefaultEnv(
		t,
		[]mock.MockBackendOption{
			mock.WithRequestMatchHandler(
				mock.GetReposPullsByOwnerByRepoByPullNumber,
				http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
					w.Write(mock.MustMarshal(mockedPullRequest))
				}),
			),
			mock.WithRequestMatchHandler(
				mock.DeleteReposGitRefsByOwnerByRepoByRef,
				http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
				   isDeleteHeadBranchRequestPerformed = true
				   w.WriteHeader(http.StatusNoContent)
				}),
			),
		},
		nil,
		aladino.MockBuiltIns(),
		nil,
	)

	err := deleteHeadBranch(mockedEnv, []aladino.Value{})

	assert.Nil(t, err)
	assert.True(t, isDeleteHeadBranchRequestPerformed, "the head branch should have been deleted")
}
```

2022-10-18 12:35 UTC, shay2025 commented on plugins/aladino/actions/deleteHeadBranch_test.go
> +func TestDeleteHeadBranch_SuccessClosed(t *testing.T) {
The same comment to the `TestDeleteHeadBranch_SuccessMerged` related to the `isDeleteHeadBranchRequestPerformed` is applicable here.

2022-10-18 12:35 UTC, shay2025 commented on plugins/aladino/actions/deleteHeadBranch_test.go
> +func TestDeleteHeadBranch_SuccessClosed(t *testing.T) {
This test function and the `TestDeleteHeadBranch_SuccessMerged` seem very similar only varying the `mockedPullRequest`. What about we apply Table-Driven tests here?
We could also include the `TestDeleteHeadBranch_WhenPRIsNotMergedOrClosed` test function as well.
If this seems a bit complex, let me know :slightly_smiling_face:

2022-10-18 14:19 UTC, shay2025 requested changes

2022-10-18 14:19 UTC, shay2025 commented on plugins/aladino/actions/deleteHeadBranch_test.go
> +	isDeleteHeadBranchRequestPerformed := false
This variable should be declared inside each test case like:
```
	for _, testCase := range testCases {
		t.Run(testCase.name, func(t *testing.T) {
              isDeleteHeadBranchRequestPerformed := false
...
```
This because the variable should not be shared between tests.

2022-10-18 14:19 UTC, shay2025 commented on plugins/aladino/actions/deleteHeadBranch_test.go
> +func TestDeleteHeadBranch(t *testing.T) {
There is no need to declare so many mock pull requests.
Instead of separating the mock pr handlers we could pass a `clientOptions []mock.BackendOption` and pass that instead and this may avoid declaring so many mock pull requests since they can be passed directly to the appropriate handlers.

2022-10-18 14:23 UTC, shay2025 commented on plugins/aladino/actions/deleteHeadBranch_test.go
> +	isDeleteHeadBranchRequestPerformed := false
This can stay as it is for now. Check the other comments please :slightly_smiling_face:

2022-10-18 16:27 UTC, shay2025 requested changes

2022-10-18 16:27 UTC, shay2025 commented on plugins/aladino/actions/deleteHeadBranch_test.go
> +			}
Instead of adopting a strategy like this, you can follow what we had done in previous handling of such cases where instead of providing `err error` in the tests you can provide the error message and do:
```
gotErr := deleteHeadBranch(mockedEnv, []aladino.Value{})

if gotErr != nil && gotErr.(*github.ErrorResponse).Message != test.wantErr {
	assert.FailNow(t, "DeleteHeadBranch() error = %v, wantErr %v", gotErr, test.wantErr)
}
```

2022-10-19 05:05 UTC, zolamk commented on plugins/aladino/actions/deleteHeadBranch_test.go
> +			}
What happens in test scenarios where you are expecting an error, but an error isn't returned 🤔, i don't think this would work in those scenarios @shay2025 , what do you think?

2022-10-19 08:19 UTC, shay2025 commented on plugins/aladino/actions/deleteHeadBranch_test.go
> +			}
Yes, you are correct.

2022-10-19 08:25 UTC, shay2025 requested changes
Almost there :slightly_smiling_face:

2022-10-19 08:25 UTC, shay2025 commented on plugins/aladino/actions/deleteHeadBranch_test.go
> +		name                    string
You could do instead:
```
tests := map[string]struct {
		clientOptions           []mock.MockBackendOption
		deleteShouldBePerformed bool
		err                     error
}{
       {
			"when pull request is closed": {
			        clientOptions: []mock.MockBackendOption{
				    mock.WithRequestMatchHandler(
					       mock.GetReposPullsByOwnerByRepoByPullNumber,
...

for name, test := range tests {
	t.Run(name, func(t *testing.T) {
...
```

2022-10-20 10:03 UTC, shay2025 approved these changes

2022-10-20 11:19 UTC, merged