feat: assign reviewers command
reviewpad/reviewpad pull request #414
Opened 2022-10-24 15:33 UTC by zolamk

## Description
This PR allows assigning reviewers to a PR by adding a comment to it. Below is the format the command should take

`/reviewpad assign-reviewers <comma_separated_list_of_reviewers> <total_required_reviewers> <review_policy>`

### Example
`/reviewpad assign-reviewers marcelosousa, shay2025, ferreiratiago 2 random`

the command can also be used by just passing a list of reviewers as

`/reviewpad assign-reviewers marcelosousa, shay2025, ferreiratiago`

the review strategy can also be omitted while providing total required reviewers

`/reviewpad assign-reviewers marcelosousa, shay2025, ferreiratiago 2`

## Related issue

Closes #408 

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?
Unit tests

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-10-25 14:27 UTC, shay2025 requested changes
Would it make sense to include the commands in their own package? We will have a lot of commands that will be implemented so the file `commands.go` would be too big.
Also, when a command is made through the comment, the action is as expected triggered but it runs the whole `reviewpad.yml` file again. It would be nice if only the workflow related to the command is run.

2022-10-25 14:31 UTC, shay2025 commented
@zolamk upon testing, another thing happened, when executing `/reviewpad assign-reviewers ferreiratiago, shay2025` I received the following error: `strconv.Atoi: parsing "": invalid syntax`.

2022-10-26 07:19 UTC, zolamk commented
> Would it make sense to include the commands in their own package? We will have a lot of commands that will be implemented so the file `commands.go` would be too big...

Yeah, it makes sense to move it into its own package, but since we will get an import cycle error, we can add the available commands on the env, what do you think @shay2025?

2022-10-26 08:21 UTC, shay2025 commented
> > Also, when a command is made through the comment, the action is as expected triggered but it runs the whole `reviewpad.yml` file again. It would be nice if only the workflow related to the command is run.
> 
> We can clear the rest of the workflows @shay2025, if we don't want them to run when a command is commented

Yes, that would be ideal but won't that affect the running of the original workflows when the action is triggered not by a command?

2022-10-26 08:23 UTC, shay2025 commented
> > Would it make sense to include the commands in their own package? We will have a lot of commands that will be implemented so the file `commands.go` would be too big...
> 
> Yeah, it makes sense to move it into its own package, but since we will get an import cycle error, we can add the available commands on the env, what do you think @shay2025?

Yes, we could do that. But it still remains the situation that since we will have a lot of command, it makes sense that each command has its file and maybe the env can have a map of the command like it does with the built-ins.

2022-10-26 08:23 UTC, zolamk commented
> > > Also, when a command is made through the comment, the action is as expected triggered but it runs the whole `reviewpad.yml` file again. It would be nice if only the workflow related to the command is run.
> > 
> > 
> > We can clear the rest of the workflows @shay2025, if we don't want them to run when a command is commented
> 
> Yes, that would be ideal but won't that affect the running of the original workflows when the action is triggered not by a command?

We'll only be clearing them in case a command is activated, the rest of the time the workflows in the `reviewpad.yml` file will execute as normal

2022-10-26 09:29 UTC, shay2025 requested changes

2022-10-26 09:29 UTC, shay2025 commented on engine/exec.go
> +
Maybe we could try to move this code block to the beginning of the `Eval` func and at the end of the commands processing we could just return the program.
```
// a program is a list of statements to be executed based on the command, workflow rules and actions.
program := BuildProgram(make([]*Statement, 0))

// process commands
if env.TargetEntity.EventName == "issue_comment" {
  ...
  return program, nil
}
```
That way we only deal with the commands with no processing related to the `reviewpad.yml` file and we don't need to add:
```
file.Rules = []PadRule{}
file.Workflows = []PadWorkflow{}
```
in order to clear the rules and workflows.

2022-10-26 09:41 UTC, zolamk commented on engine/exec.go
> +
🤔 I think we actually need to move it down, right after labels and groups have been processed because in the future we might have a command that relies on the groups defined in the files or something, what do you think?

2022-10-26 10:57 UTC, shay2025 commented on engine/exec.go
> +
Yes, you're right :slightly_smiling_face:

2022-10-26 12:03 UTC, shay2025 requested changes
Almost there :slightly_smiling_face:

2022-10-26 12:03 UTC, shay2025 commented on engine/commands/assign_reviewer_command.go
> +func AssignReviewerCommand(matches []string) ([]string, error) {
Since this is inserted in the commands package we know that we are dealing with `assign reviewers` in a command context so I believe there is no need to mention `Command`.
```suggestion
func AssignReviewer(matches []string) ([]string, error) {
```

The same applies to `assignReviewerCommandRegex` that can be `assignReviewerRegex`. And also the file names, which can be `assignReviewer.go` and `assignReviewer_test.go` instead of `assign_reviewer_command.go` and `assign_reviewer_command_test.go`, respectively.

2022-10-26 14:20 UTC, shay2025 commented
@zolamk when you can please update the branch with the latest version in `main`.

2022-10-26 17:01 UTC, shay2025 approved these changes

2022-10-27 08:49 UTC, merged