Add unit tests for `$removeLabel` action builtin
reviewpad/reviewpad pull request #42
Opened 2022-07-01 15:17 UTC by shay2025

This pull requests introduces the following:
- removal of args length and type check in removeLabel action builtin since these checks are already made before the action execution;
- add labels to the pull request mocks;
- add unit tests for the `removeLabel` action builtin.

2022-07-04 15:43 UTC, ferreiratiago requested changes
Please have a look at the comments.

[reviewpad-sig]: <>
[View on **Reviewpad**](https://beta.reviewpad.com/review/github.com/reviewpad/reviewpad/pull/42?codereviewid=7e6eea98-7c42-4538-9deb-2c4e9f465381)

2022-07-04 15:43 UTC, ferreiratiago commented on plugins/aladino/actions/removeLabel_test.go
> +	assert.Equal(t, err.(*github.ErrorResponse).Message, failMessage)
We should be using `EqualError` for these cases.

```go
assert.EqualError(t, err, failMessage)
```

2022-07-04 15:43 UTC, ferreiratiago commented on plugins/aladino/actions/removeLabel_test.go
> +func TestRemoveLabel_WhenLabelIsNotAppliedToPullRequest(t *testing.T) {
I'm a bit confused with this test. From the description it say `WhenLabelIsNotAppliedToPullRequest` but then we expect the label to be removed `labelRemoved = true` and then on line 63 the description says `The label should not be removed`. Can you please clarify this?

2022-07-04 15:43 UTC, ferreiratiago commented on plugins/aladino/actions/removeLabel_test.go
> +				Name: github.String("bug"),
Shouldn't we use `label` instead of the literal `bug`?

```go
Name: github.String(label)
```

2022-07-04 15:43 UTC, ferreiratiago commented on plugins/aladino/actions/removeLabel_test.go
> +				Name: github.String("enhancement"),
[reviewpad-sig]: <>
[Link to Comment](https://beta.reviewpad.com/review/github.com/reviewpad/reviewpad/pull/42#comment-5477e452-f867-469e-b71f-d2845f9e5e37)

2022-07-04 15:43 UTC, ferreiratiago commented on plugins/aladino/actions/removeLabel_test.go
> +	var labelRemoved bool
I would suggest to rename this to `isLabelRemoved`.

2022-07-04 15:43 UTC, ferreiratiago commented on plugins/aladino/actions/removeLabel_test.go
> +	label := "enhancement"
I would suggest to rename this to `wantLabel`.

2022-07-05 10:18 UTC, shay2025 commented on plugins/aladino/actions/removeLabel_test.go
> +func TestRemoveLabel_WhenLabelIsNotAppliedToPullRequest(t *testing.T) {
@ferreiratiago this follows a similar logic as [`TestCommentOnce_WhenCommentAlreadyExists`](https://github.com/reviewpad/reviewpad/blob/817cb2d3b356ed6b6edda465dad6aac1c7f22ec3/plugins/aladino/actions/commentOnce_test.go#L52-L82)
We need to test this scenario:
https://github.com/reviewpad/reviewpad/blob/f5bf22ce41fff44666018898467991aaa5d9379e/plugins/aladino/actions/removeLabel.go#L39-L41
But the result of this scenario is only a return of `nil` error which I believe isn't enough since if a label is successfully removed it will also return a `nil` error.
So to counter this, I propose we use a flag `labelRemoved` which will be an indicator if the request to remove a label was executed and if so then the condition `labelIsAppliedToPullRequest` is `true` and what we want to cover won't be covered.

2022-07-05 10:49 UTC, shay2025 commented on plugins/aladino/actions/removeLabel_test.go
> +	assert.Equal(t, err.(*github.ErrorResponse).Message, failMessage)
@ferreiratiago Yes I agree but when handling `github.ErrorResponse` it becomes more complicated, i.e, the readability of the handling isn't neat:
```
args := []aladino.Value{aladino.BuildStringValue("test")}
err = errors.New(removeLabel(mockedEnv, args).(*github.ErrorResponse).Message)

assert.EqualError(t, err, errorMessage)
```

2022-07-05 14:25 UTC, ferreiratiago approved these changes
LGTM

2022-07-05 16:07 UTC, merged