feat: comment metric report when pr is merged
reviewpad/reviewpad pull request #427
Opened 2022-10-26 17:45 UTC by zolamk

## Description
This PR comments metrics reports when a pull request is merged.

## Related issue

Closes #407 

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-11-03 10:12 UTC, shay2025 requested changes
Why did you disregard the previous reviewpad report?
Both reports should exist and they are shown to the user if the `mode` property in the `reviewpad.yml` is set to `verbose`.

2022-11-03 10:36 UTC, zolamk commented
> Why did you disregard the previous reviewpad report? Both reports should exist and they are shown to the user if the `mode` property in the `reviewpad.yml` is set to `verbose`.

The reason I made it into a separate report is because the metrics should only be reported when the PR is merged but we can also combine the two reports into one and check if the PR is merged when performing the report, what do you think @shay2025 ?

2022-11-03 10:59 UTC, shay2025 commented
@zolamk what is happening is that the previous report annotation does not seem to exist. These are two different reports. One with the reviewpad executions (the already existing one) and the metrics report. And what it seems to have been done is that the annotation that helped identify the first report was disregarded.
Both reports should have separared implementations, i.e, the implementation of the first report that already existed should remain untouched and a new report implementation should be done for the metrics report.
The only thing in common for both reports should be that they are only shown to the user if the `mode` property in the `reviewpad.yml` file is set  to `verbose`.

2022-11-03 13:20 UTC, shay2025 commented
@zolamk the report doesn't seem to be printing the time data correctly. I opened a pull request that was merged 1 hour after it was opened and the `coding time` is incorrect.
![image](https://user-images.githubusercontent.com/61353903/199731384-393f0854-1017-413a-a069-8cf6b372034c.png)

2022-11-03 13:25 UTC, zolamk commented
> @zolamk the report doesn't seem to be printing the time data correctly. I opened a pull request that was merged 1 hour after it was opened and the `coding time` is incorrect. ![image](https://user-images.githubusercontent.com/61353903/199731384-393f0854-1017-413a-a069-8cf6b372034c.png)

@shay2025 I thought coding time was calculated as the difference between the first commit and the time the pull request was created, or is it supposed to be the time the pull request was merged?

2022-11-03 13:41 UTC, shay2025 commented
> > @zolamk the report doesn't seem to be printing the time data correctly. I opened a pull request that was merged 1 hour after it was opened and the `coding time` is incorrect. ![image](https://user-images.githubusercontent.com/61353903/199731384-393f0854-1017-413a-a069-8cf6b372034c.png)
> 
> @shay2025 I thought coding time was calculated as the difference between the first commit and the time the pull request was created, or is it supposed to be the time the pull request was merged? I think that was how it was defined on the issue and that's how the people at linearb define it https://linearb.io/blog/reducing-coding-time/

The time shown should be precise, i.e, say the exact seconds/minutes/days I believe.

2022-11-03 17:27 UTC, shay2025 requested changes

2022-11-03 17:27 UTC, shay2025 commented on utils/time.go
> +	years, months, days, hours, minutes, seconds := timex.Diff(x, y)
Why are we using the `timex.Diff` method? We could use the `Sub` method from the `time` library:
```
years, months, days, hours, minutes, seconds := x.Sub(y)
```
That way we don't need to import another library.

2022-11-03 17:27 UTC, shay2025 commented on utils/time.go
> +	return strings.Join(parts[:l-1], ", ") + ", and " + parts[l-1]
There is no need for the comma in ", and".

2022-11-03 17:27 UTC, shay2025 commented on utils/time.go
> +		return parts[0] + ", and " + parts[1]
There is no need for the comma in ", and".

2022-11-04 06:25 UTC, zolamk commented on utils/time.go
> +	years, months, days, hours, minutes, seconds := timex.Diff(x, y)
The thing is [Sub](https://pkg.go.dev/time#Time.Sub) gives you a `Duration`, it doesn't divide the diff into it's `year`, `month`, `days`, `hours`, `minutes`, `seconds` parts but yeah it might not be justifiable to include a new dependency for one function, if you'd prefer we can just implement the diff ourselves, what do you think?

2022-11-04 09:28 UTC, shay2025 commented on utils/time.go
> +	years, months, days, hours, minutes, seconds := timex.Diff(x, y)
Yes, it would be preferable to have our own method like `func diff(a, b time.Time) (year, month, day, hour, min, sec int)`.

2022-11-08 15:53 UTC, ferreiratiago requested changes

2022-11-08 15:53 UTC, ferreiratiago commented on runner.go
> +	if targetEntity.Kind == handler.PullRequest && targetEntity.EventName == "pull_request" && targetEntity.EventAction == "closed" {
Can we add this condition into a single function and call it `isPullRequestReadyForReportMetrics`.

2022-11-08 15:53 UTC, ferreiratiago commented on utils/time.go
> +func FormatTimeDiff(x time.Time, y time.Time) string {
```suggestion
func ReadableTimeDiff(x time.Time, y time.Time) string {
```

2022-11-08 16:50 UTC, zolamk commented on codehost/github/pull_requests.go
> +	return nil, nil
Yeah makes sense, should be faster as well because we can combine the GraphQL queries

2022-11-08 17:27 UTC, zolamk commented on lang/aladino/interpreter.go
> +		r := ReviewpadMetricReportCommentAnnotation + "\n## 📈 Pull Request Metrics\n" + report.String()
The thing is the markdown won't be treated as a header unless we have that space there, I think we need to keep the space

2022-11-08 17:51 UTC, ferreiratiago commented
@zolamk can you please rebase the pull request with the base branch? 🙏

2022-11-08 17:56 UTC, zolamk commented
> @zolamk can you please rebase the pull request with the base branch? pray

sure thing, on it.

2022-11-08 18:01 UTC, zolamk commented
> @zolamk can you please rebase the pull request with the base branch? pray

done @ferreiratiago

2022-11-08 20:33 UTC, ferreiratiago commented on lang/aladino/interpreter.go
> +		r := ReviewpadMetricReportCommentAnnotation + "\n## 📈 Pull Request Metrics\n" + report.String()
You're right 👍

2022-11-08 21:06 UTC, merged

2022-11-10 10:33 UTC, ferreiratiago commented
<!--@annotation-reviewpad-metric-report-->
## 📈 Pull Request Metrics
**💻 Coding Time**: 3 minutes and 9 seconds
**🛻 Pickup Time**: 7 days, 16 hours, 27 minutes and 15 seconds
**👀 Review Time**: 5 days, 10 hours, 53 minutes and 56 seconds