feat: close with state reason
reviewpad/reviewpad pull request #430
Opened 2022-10-27 14:42 UTC by zolamk

## Description
This PR introduces an option second parameter to the `$close` built-in action, which allows us to specify the reason an issue was closed.
- add second parameter to `$close` built-in action

## Related issue

Closes #299 

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?
Manual & Unit Tests.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-10-31 09:33 UTC, marcelosousa commented
Hi @zolamk could you please separate the dependency upgrade from the functionality in this PR? Thanks!

2022-10-31 09:37 UTC, zolamk commented
> Hi @zolamk could you please separate the dependency upgrade from the functionality in this PR? Thanks!

Sure @marcelosousa

2022-11-03 11:11 UTC, shay2025 requested changes
Some minor suggestions.

2022-11-03 11:11 UTC, shay2025 commented on engine/transform.go
> +	return r.ReplaceAllString(str, `$$close("$1", "completed")`)
Isn't there a duplicate `$`?

2022-11-03 11:29 UTC, zolamk commented on engine/transform.go
> +	return r.ReplaceAllString(str, `$$close("$1", "completed")`)
the `ReplaceAllString` method treats `$` as a capture group reference so you have to put 2 of them if you want a literal `$` in there

2022-11-03 11:38 UTC, zolamk commented on lang/aladino/mocks.go
> +
Yeah, touching the `MockDefaultEnv` method required changes in a lot of places, but I can do it now or later if you prefer

2022-11-03 11:51 UTC, shay2025 commented on lang/aladino/mocks.go
> +
Let's do it in a separate PR :slightly_smiling_face:

2022-11-03 13:54 UTC, shay2025 approved these changes

2022-11-08 16:48 UTC, merged