feat: improve assign reviewer command
reviewpad/reviewpad pull request #433
Opened 2022-10-31 15:57 UTC by zolamk

## Description
This PR improves the `assign-reviewers` command to streamline configuration passing
### Examples
- `/reviewpad assign-reviewers john,jane`
- `/reviewpad assign-reviewers john,jane --total-reviewers=1`
- `/reviewpad assign-reviewers jane,john --total-reviewers=1 --review-policy=round-robin`
- `/reviewpad assign-reviewers jane,john --review-policy=random`

List any dependencies that are required for this change (if applicable.)
- https://github.com/mattn/go-shellwords

## Related issue

Closes #428 

## Type of change

Improvements (non-breaking change without functionality)

## How was this tested?
Manual & Unit Tests.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have run `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-11-04 11:29 UTC, shay2025 requested changes

2022-11-04 11:29 UTC, shay2025 commented on engine/commands/assignReviewer_test.go
>  		"when only two reviewers is provided": {
```
"when only two reviewers are provided"
```

2022-11-04 11:29 UTC, shay2025 commented on engine/commands/assignReviewer_test.go
>  	}
We should also add the test case: `"when number of provided reviewers is less than requested reviewers"`

2022-11-04 11:29 UTC, shay2025 commented on engine/exec.go
> +		args, err := shellwords.Parse(comment)
We should not need this extra library because the args should be separated by spaces I believe.

2022-11-04 11:56 UTC, zolamk commented on engine/commands/assignReviewer.go
> +	flags.Int8P("total-reviewers", "t", 1, "Total number of reviewers, default value is 1")
We are using `1` reviewer by default, should we make it all by default?

2022-11-04 12:07 UTC, zolamk commented on engine/commands/assignReviewer_test.go
>  	}
currently if the number of provider reviewers is less than the requested reviewers the command will still build an action and add it to the program

2022-11-04 12:07 UTC, zolamk commented on engine/commands/assignReviewer_test.go
>  	}
should we have a validation in place for it?

2022-11-04 13:37 UTC, zolamk commented on engine/commands/assignReviewer.go
> +		SilenceUsage:  true,
It shouldn't since we are using `RunE` and handling the errors ourselves, any errors should be returned by `Execute` at which point we handle them by updating the comment with the error

2022-11-04 13:45 UTC, zolamk commented on engine/exec.go
> +		args, err := shellwords.Parse(comment)
I think spaces inside of quotations and things like those need to be considered, but yeah we can use regexp to parse it

2022-11-04 14:34 UTC, shay2025 commented on engine/commands/assignReviewer_test.go
>  	}
There is no need for the validation I believe. The `$assignReviewer` built-in when receives a list of reviewers whose size is less than the number of requested reviewers then it will consider the number of requested reviewers to be the size of the provided list of reviewers instead.

2022-11-04 14:39 UTC, shay2025 commented on engine/exec.go
> +		args, err := shellwords.Parse(comment)
I noticed the examples you provided in the PR description that the flags values are preceded by an `=`. Do the commands still work if it is something like `/reviewpad assign-reviewers john,jane --total-reviewers 1`? If not, we should consider to also support that.
If so, then we can leave the `shellwords` library I believe.

2022-11-04 14:41 UTC, shay2025 commented on engine/exec.go
> +		args, err := shellwords.Parse(comment)
This that library can still separate the arguments by the spaces usage.

2022-11-04 14:43 UTC, shay2025 commented on engine/commands/assignReviewer.go
> +	flags.Int8P("total-reviewers", "t", 1, "Total number of reviewers, default value is 1")
Yes, because that's the behaviour of the `$assignReviewer` built-in: https://docs.reviewpad.com/guides/built-ins#assignreviewer

2022-11-05 08:38 UTC, zolamk commented on engine/exec.go
> +		args, err := shellwords.Parse(comment)
Yeah, the library can handle those cases as well, so I believe we should keep it

2022-11-09 12:06 UTC, shay2025 approved these changes
After running some tests, the feature seems to be working as expected :slightly_smiling_face: 
There is only a minor strange behavior which is upon the execution of the command the existing report will be edited where the `execution actions` block is replaced with the command action. After the command execution finishes, the report is edited again with the previous content.
But this behavior can be dealt in a separate issue.


https://user-images.githubusercontent.com/61353903/200826099-ab6862f0-00d5-420f-be24-079ca92ceced.mp4

2022-11-09 12:07 UTC, shay2025 commented
@zolamk when you can please resolve the conflicts :slightly_smiling_face:

2022-11-15 11:13 UTC, ferreiratiago requested changes
The major change we need to do here is to not use `TargetEntity` to append all info not related to the entity but with the action to be applied to the entity.

2022-11-15 12:04 UTC, zolamk commented on handler/processors.go
>  	EventName   string
`Kind` represents what the target entity is currently `pull request` or `issue`, `EventName` is the actual event that happened which could be things like `issue_comment`, `pull_request_review`, `discussion_comment`...

2022-11-15 12:44 UTC, zolamk commented on engine/exec.go
> +			return nil, err
I haven't looked into how other bots handle it but, I think as far as user experience is concerned, editing the comment to show what went wrong is a good experience

2022-11-15 12:47 UTC, zolamk commented on engine/exec.go
> +			return nil, err
As for the user editing the comment, we are only processing commands on comment created event since we didn't want to get into some sort of loop where reviewpad keeps getting triggered by its own comment so the user editing their comment shouldn't matter, What do you think @ferreiratiago

2022-11-15 12:49 UTC, zolamk commented on handler/processors.go
> +	Comment     *github.IssueComment
Yeah, make much better sense to have another structure for this

2022-11-15 12:59 UTC, zolamk commented on handler/processors.go
> +	Comment     *github.IssueComment
We already have an `ActionEvent` should we reuse that or introduce a new, I say introduce a new because we might not need all the fields already available in the current `ActionEvent` what do you think @ferreiratiago

2022-11-23 11:21 UTC, zolamk commented on handler/processors.go
> +	Comment     *github.IssueComment
@ferreiratiago I've submitted an update for this as a separate pr #459 , i'll rebase this after that's reviewed and merged

2022-11-24 11:16 UTC, ferreiratiago requested changes
The pr #459 was merged. Can you please @zolamk update this pr? Thanks 🙏

2022-11-24 12:12 UTC, ferreiratiago approved these changes

2022-11-24 12:13 UTC, merged