feat: add hasBinaryFile built-in function
reviewpad/reviewpad pull request #480
Opened 2022-11-28 13:49 UTC by zolamk

## Description
This PR adds a new `hasBinaryFile` built-in function that returns a boolean value indicating whether a PR has binary file changes.

## Related issue

Closes #477 

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?
Unit & Manual Tests

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-11-28 22:29 UTC, marcelosousa requested changes
Thanks @zolamk ! A couple of comments from review 🙏

2022-11-28 22:29 UTC, marcelosousa commented on plugins/aladino/functions/hasBinaryFile.go
> +		// there won't be any patch for binary files, we can use that to check if pr has binary file changes
```suggestion
		// file is binary if GitHub does not display a textual diff
```

2022-11-28 22:29 UTC, marcelosousa commented on plugins/aladino/functions/hasBinaryFile.go
> +	for _, patch := range patch {
Please do not use the same variable on the left side - it's very confusing. I suggest `patchFile`.

2022-11-28 22:29 UTC, marcelosousa commented on plugins/aladino/functions/hasBinaryFile.go
> +			break
I think you can simply return here.

2022-11-28 22:29 UTC, marcelosousa commented on plugins/aladino/functions/hasBinaryFile.go
> +		if patch.Repr.GetPatch() == "" {
FYI: I'm not sure if this is really true. I think the same might happen with git submodules.

Anyway, this might a good approximation so I suggest we leave it as is.

For reference, it is possible to use the GitHub GraphQL API to check if a file is binary or not:

```gql
{
  repository(owner: $owner, name: $name) {
    object(expression: "BRANCH:FILEPATH") {
      ... on Blob{
        isBinary
      }
    }
  }
}
```

For example,
```gql
{
  repository(owner: "reviewpad", name: "reviewpad") {
    object(expression: "main:go.sum") {
      ... on Blob{
        isBinary
      }
    }
  }
}
```

2022-11-28 22:29 UTC, marcelosousa commented on plugins/aladino/functions/hasBinaryFile_test.go
> +					Patch:    github.String(""),
Please provide a link to a PR that modifies a binary file so that we can confirm that it produces an empty patch.

2022-11-29 02:23 UTC, zolamk commented on plugins/aladino/functions/hasBinaryFile.go
> +		if patch.Repr.GetPatch() == "" {
Yeah, after a short discussion with @ferreiratiago yesterday, since this isn't a documented behavior it might be better to go with this, I'll update the PR, Thank You.

2022-11-29 09:46 UTC, zolamk commented on plugins/aladino/functions/hasBinaryFile_test.go
> +					Patch:    github.String(""),
I've updated the PR to use the GraphQL API since the patch thing ins't document behavior.

2022-11-29 09:48 UTC, zolamk commented on plugins/aladino/functions/hasBinaryFile_test.go
> +					Patch:    github.String(""),
If just checking the patch is preferable, I can revert it @marcelosousa

2022-11-29 09:55 UTC, marcelosousa approved these changes
LGTM @zolamk . Please don't forget to add a PR with the docs repository!

2022-11-29 10:03 UTC, ferreiratiago approved these changes

2022-11-29 12:48 UTC, merged