feat: have all checks run completed
reviewpad/reviewpad pull request #484
Opened 2022-11-29 13:35 UTC by zolamk

## Description
This PR introduces the `$haveAllChecksRunCompleted` built-in function, the function returns a boolean value indicating if all check runs completed with an optional ignore list and conclusion.
### Examples
- `$haveAllChecksRunCompleted()` (all checks run completed)
- `$haveAllChecksRunCompleted(["integration-test"])` (all checks run completed except for the `integration-test` check run)
- `$haveAllChecksRunCompleted([], "success")` (all checks run completed and had a success conclusion)

## Related issue

Closes #481 

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?
Unit & Manual Tests

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-11-30 12:56 UTC, ferreiratiago requested changes

2022-11-30 12:56 UTC, ferreiratiago commented on plugins/aladino/functions/haveAllChecksRunCompleted.go
> +func HaveAllChecksRunComplted() *aladino.BuiltInFunction {
Typo

### 
```suggestion
func HaveAllChecksRunCompleted() *aladino.BuiltInFunction {
```

2022-11-30 12:56 UTC, ferreiratiago commented on plugins/aladino/functions/haveAllChecksRunCompleted.go
> +		}
Can we split this into 2 different conditions for better reading?

```suggestion
		if checkRun.GetStatus() != "completed" {
			return aladino.BuildBoolValue(false), nil
		}
		
		if  conclusion.Val != "" && checkRun.GetConclusion() != conclusion.Val {
			return aladino.BuildBoolValue(false), nil
		}
```

2022-11-30 12:56 UTC, ferreiratiago commented on plugins/aladino/functions/haveAllChecksRunCompleted.go
> +	ghCommits, err := e.GetGithubClient().GetPullRequestCommits(e.GetCtx(), owner, repo, number)
I'm sure this was already discussed but can you please make sure that the list of commits is in chronological order? And please add the reference that supports that. Thanks 🙏

2022-11-30 15:09 UTC, zolamk commented on plugins/aladino/functions/haveAllChecksRunCompleted.go
> +	ghCommits, err := e.GetGithubClient().GetPullRequestCommits(e.GetCtx(), owner, repo, number)
Github returns the list of commits in chronological order which is referenced here https://github.blog/changelog/2020-07-14-pull-request-commits-now-ordered-chronologically/

2022-11-30 15:10 UTC, zolamk commented on plugins/aladino/functions/haveAllChecksRunCompleted.go
> +	ghCommits, err := e.GetGithubClient().GetPullRequestCommits(e.GetCtx(), owner, repo, number)
But since it is more efficient to just get the last commit SHA using the GraphQL API, the PR has been modified to do so.

2022-12-01 12:22 UTC, ferreiratiago approved these changes

2022-12-01 12:23 UTC, merged