feat: command error as comment
reviewpad/reviewpad pull request #502
Opened 2022-12-05 07:10 UTC by zolamk

## Description
Currently, a command might be syntactically correct but during execution of the generated program for a command an error might happen which makes it seem like it's a reviewpad error when in a reality it was the command that failed because of wrong input so this PR provides feedback to the user in the form of a GitHub comment.

## Related issue

Closes #471 

## Type of change

Improvements (non-breaking change without functionality)

## How was this tested?
Unit tests and Manual tests

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-12-20 14:42 UTC, ferreiratiago commented
This pull request is on hold due to low priority.

2023-01-02 17:18 UTC, ferreiratiago requested changes
Sorry for the late review. Please have a look at the comment 🙏

2023-01-02 17:18 UTC, ferreiratiago commented on lang/aladino/env.go
> +	EventData                *handler.EventData
Why do we need `EventData`? `EventPayload` should be enough for what we need here. WDYT?

2023-01-02 17:18 UTC, ferreiratiago commented on engine/program.go
> +	IsFromCommand bool
`IsFromCommand` should be another property of the `env` in which the program is running. I would suggest moving this into the `BaseEnv`. WDYT?

2023-01-03 12:27 UTC, zolamk commented on lang/aladino/env.go
> +	EventData                *handler.EventData
Yeah, makes perfect sense, thank you

2023-01-03 19:28 UTC, zolamk commented on engine/program.go
> +	IsFromCommand bool
This one I think better to keep it in the program since we are checking if it's a command after the `BaseEnv` is built I think, what do you think @ferreiratiago

2023-01-13 18:19 UTC, ferreiratiago approved these changes

2023-01-13 18:19 UTC, merged