feat: join built-in function
reviewpad/reviewpad pull request #542
Opened 2022-12-15 14:42 UTC by zoldater

## Description

The pull request introduces the `$join()` built-in function that returns a string value concatenating array elements with separator.

## Motivation

`sprintf` function replaces existing specifiers with the values from `arguments_list `. For this reason passing `$group()`, `$team()`, `$assignees()` or any array of arbitrary size as `arguments_list` could be correct.

Proposed change makes it possible to join arrays into string to replace only one format specifier.

## Example

- `$sprintf("These changes require approval by team 'a': %s", [$join($group("a"))])`

## Related issue

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?

Unit tests.

## Checklist

- [x ] I have performed a self-review of my code
- [ x] I have added tests that prove my fix is effective or that my feature works 
- [ x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [ ] Ask: this pull request requires a code review before merge

2022-12-15 16:22 UTC, marcelosousa reviewed
Many thanks for this PR 🙌  I've left a comment related to the transform of the join built-in as it is not working for nested calls. I believe this is a broader issue of the way we are doing these transformations and should be addressed in a different issue. @ferreiratiago should I open an issue for that so that we can unblock this PR?

For the rest, it's looking good - thanks!

2022-12-15 16:22 UTC, marcelosousa commented on engine/transform_internal_test.go
> +		},
The transform has a limitation that it doesn't work for nested $join statements. For example:

```
        "nested join with empty separators ": {
			arg:     `$join([$join(["a","b"]), "c"])`,
			wantVal: `$join([$join(["a","b"], " "), "c"], " ")`,
		},
```

2022-12-15 16:26 UTC, marcelosousa commented
Test coverage is good!

2022-12-16 09:51 UTC, zoldater commented on engine/transform_internal_test.go
> +		},
Thanks @marcelosousa !
I've added the test and fixed issue with recursion.

2022-12-19 11:25 UTC, zoldater commented
Hi @ferreiratiago and @marcelosousa !
I fixed the issue with nested join calls and added proposed test to `engine/transform_internal_test.go`. So it should not be necessary to open new issue for that.

2022-12-20 13:31 UTC, ferreiratiago requested changes

2022-12-20 13:31 UTC, ferreiratiago commented on engine/transform.go
> +	r := regexp.MustCompile(`\$join\(((\[.*\])|(\$(team|group)\("[^"]*"\))|(\$assignees\(\)))(,\s*"([^"]*)")?\)`)
What's the reasoning behind `team`, `group`, and `assignees`? I may be missing something 😅

Isn't a simpler regex enough?
```suggestion
	r := regexp.MustCompile(`\$join\((\[.*\]|([^,]*))(,\s*"([^"]*)")?\)`)
```

If we have the literal values `team`, `group`, and `assignees`, we need to keep updating this transform every time there's a new built-in that returns a []string. For instance, [$filePaths()](https://github.com/reviewpad/reviewpad/issues/538).

2022-12-20 15:26 UTC, zoldater commented on plugins/aladino/functions/join.go
> +		}
Done.

2022-12-20 15:27 UTC, zoldater commented on engine/transform.go
> +	r := regexp.MustCompile(`\$join\(((\[.*\])|(\$(team|group)\("[^"]*"\))|(\$assignees\(\)))(,\s*"([^"]*)")?\)`)
Thanks for pointing this out! Simplified the regex.

2022-12-21 09:25 UTC, ferreiratiago requested changes
One unit test missing. Other than that it's perfect 🙌

2022-12-21 09:25 UTC, ferreiratiago commented on plugins/aladino/functions/join.go
> +			return nil, fmt.Errorf("join: invalid element of kind %v", v.Kind())
We are very close. Just missing the unit test for this case.

2022-12-21 10:21 UTC, zoldater commented on plugins/aladino/functions/join.go
> +			return nil, fmt.Errorf("join: invalid element of kind %v", v.Kind())
Added `TestJoin_BadType`

2022-12-21 13:19 UTC, ferreiratiago approved these changes
Perfect. Thanks for your contribution @zoldater 🙏

2022-12-21 13:19 UTC, merged