feat: content built-in function
reviewpad/reviewpad pull request #558
Opened 2022-12-20 14:11 UTC by zolamk

## Description
Adds a new built-in function `$content` that returns a `JSON` serialized string presentation of the target(pull request / issue).

## Related issue

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?
Unit tests and manual tests

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge -->

2022-12-21 16:14 UTC, ferreiratiago approved these changes

2022-12-21 20:20 UTC, marcelosousa requested changes
Thanks for this PR - please check my comment in the context_text.go file.

2022-12-21 20:20 UTC, marcelosousa commented on plugins/aladino/functions/context_test.go
> +			wantRes:      aladino.BuildStringValue(string(mockPRJSON)),
IMO, these unit tests are not enough functionally.

As a dev, I don't know exactly what is the string format that is being matched.

Please add a couple of tests that check against actual mocked strings so that we can guarantee that all understand the string format of that is returned by $context().

This is important because if we want to some regex over it, we need to understand it's format.

2022-12-21 21:03 UTC, marcelosousa commented on plugins/aladino/functions/context.go
> +func contextCode(e aladino.Env, args []aladino.Value) (aladino.Value, error) {
I think we should use the blank identifier here to state that the variable or argument is being intentionally ignored.

```suggestion
func contextCode(e aladino.Env, _ []aladino.Value) (aladino.Value, error) {
```

2022-12-22 11:30 UTC, marcelosousa approved these changes

2022-12-22 14:04 UTC, merged