feat: toJSON built-in function
reviewpad/reviewpad pull request #561
Opened 2022-12-21 09:57 UTC by zolamk

## Description
Adds a new `$toJSON` built in function that takes a string and returns a json type.

## Related issue

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?
Unit tests

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge -->

2022-12-21 16:32 UTC, ferreiratiago approved these changes

2022-12-21 16:32 UTC, ferreiratiago commented on lang/aladino/value.go
> +	// TODO: fix equals
Can you please open an issue to address this later on and add it as a comment here?

2022-12-21 20:32 UTC, marcelosousa requested changes
Please check the comment about the choice of `Val` in the `JSONValue`

2022-12-21 20:32 UTC, marcelosousa commented on lang/aladino/type.go
> +}
Turn into an one liner as in L44

2022-12-21 20:32 UTC, marcelosousa commented on lang/aladino/value.go
> +	Val interface{}
Why not use `json.RawMessage` instead of `interface{}` here? As it stands, `JSONValue` can represent any Go value which is not really what is intended. Maybe I'm missing something here :-)

2022-12-21 20:32 UTC, marcelosousa commented on lang/aladino/value_test.go
> +			y:      aladino.BuildJSONValue(10),
I'm confused as why you would want to do this.

2022-12-21 20:39 UTC, marcelosousa commented
@ferreiratiago @zolamk I have a question to ensure that we are aligned regarding JSON values in Aladino. From what I can understand, the idea is for JSON values to be a kind of internal aladino value for now correct? What is mean concretely with this question is that the only way to build a JSONValue would be use the built-in `$toJSON(...)` with a string.

2022-12-21 21:09 UTC, marcelosousa commented on plugins/aladino/functions/toJSON.go
> +		return nil, err
This is an issue for the future but we shouldn't be simply yielding errors that come from 3rd party libraries. We should be parsing those errors and converting them to our format so that users can have consistent errors messages.  (cc @ferreiratiago @zolamk @shay2025)
@ferreiratiago could we open an issue for that before merging this PR?

2022-12-21 21:11 UTC, marcelosousa commented on plugins/aladino/functions/toJSON.go
> +		return nil, err
Issue created

2022-12-22 04:00 UTC, zolamk commented on lang/aladino/value.go
> +	Val interface{}
The library we are using https://github.com/ohler55/ojg for parsing expressions and evaluating them uses the `interface{}` type, but I think we refactor it to work with `json.RawMessage` later on maybe, what do you think?

2022-12-22 04:05 UTC, zolamk commented on lang/aladino/value_test.go
> +			y:      aladino.BuildJSONValue(10),
Just a test case but integers are valid JSON as well i think.

2022-12-22 11:42 UTC, marcelosousa commented on lang/aladino/value.go
> +	Val interface{}
Alright, makes sense!

2022-12-22 11:42 UTC, marcelosousa approved these changes

2022-12-22 14:11 UTC, merged