feat: selectFromJSON and selectFromContext built-in functions
reviewpad/reviewpad pull request #563
Opened 2022-12-21 14:02 UTC by zolamk

## Description
Adds 2 new built-in functions called `$selectFromJSON` and `$selectFromContext`. The built-ins allow you to select a value form a json structure by using a [JSONPath](https://support.smartbear.com/alertsite/docs/monitors/api/endpoint/jsonpath.html) expression.

### `$selectFromJSON`

This built-in receives a json structure and a jsonpath expression and returns a value.

#### Examples
- `$selectFromJSON($toJSON($context()), "$.title")`
- `$selectFromJSON($toJSON("{\"id\": 1, \"name\": \"test\"}"), "$.name")`
- ...

### `$selectFromContext`

This built-in receives a jsonpath expression that it evaluates against the target context(issue/pull request) and returns a value

#### Examples
- `$selectFromContext("$.title")`
- `$selectFromContext("$.labels[*].name")`
- `$selectFromContext("$[\"user\"][\"login\"]")`
- `$selectFromContext("$.assignee.login")`
- `$selectFromContext("$.assignees[*].login")`
- ...

## Related issue

Closes #556 

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?
Unit tests and manual tests

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-12-21 16:51 UTC, ferreiratiago requested changes

2022-12-21 16:51 UTC, ferreiratiago commented on plugins/aladino/functions/selectFromJSON.go
> +	if res, ok := result.(string); ok {
Shouldn't we use reflect for this?
```suggestion
	if reflect.TypeOf(result).Kind() == reflect.String { {
```

2022-12-21 16:51 UTC, ferreiratiago commented on plugins/aladino/functions/selectFromJSON.go
> +		return nil, fmt.Errorf(`nothing found at path "%s"`, expr)
I don't think so we should have an error but rather an empty string.

However, we could log that `nothing found at path "%s"`.

If we throw an error we will fail every time a property is not found, which may happen if we take into account that payloads are dynamic.

2022-12-21 16:51 UTC, ferreiratiago commented on plugins/aladino/functions/selectFromJSON.go
> +	}
Why do we do this?

2022-12-21 17:25 UTC, zolamk commented on plugins/aladino/functions/selectFromJSON.go
> +	if res, ok := result.(string); ok {
Sure we could but since,  we need to cast the interface into string in the if block I think this one is shorter, what do you think?

2022-12-21 17:25 UTC, zolamk commented on plugins/aladino/functions/selectFromJSON.go
> +		return nil, fmt.Errorf(`nothing found at path "%s"`, expr)
Yeah, makes perfect sense

2022-12-21 17:29 UTC, zolamk commented on plugins/aladino/functions/selectFromJSON.go
> +	}
certain patterns can match multiple values for example `$.labels[*].name` can return multiple results if available but in cases where only one result is returned instead of encoding it as array we are encoding it as the single element

2022-12-21 21:31 UTC, marcelosousa requested changes
Overall this looks good. I understand better the choice of `interface{}` for the Val in the JSONValue to make it easy to use this 3rd party library - IMO it would be nicer to use this library with json.RawMessage . I've left some comments to improve the code! Thanks!

2022-12-21 21:31 UTC, marcelosousa commented on plugins/aladino/functions/selectFromContext.go
> +	c, err := contextCode(e, []aladino.Value{})
Since `context` doesn't take any values we can make that more explicit with:
```suggestion
	c, err := contextCode(e, nil)
```

2022-12-21 21:31 UTC, marcelosousa commented on plugins/aladino/functions/selectFromContext.go
> +}
Please don't use single letter variables; it makes the code much harder to read and it is error prone. This applies everywhere :-)

2022-12-21 21:31 UTC, marcelosousa commented on plugins/aladino/functions/selectFromContext_test.go
> +			wantErr:      errors.New("an expression fragment can not start with a '[' at 4 in $.[0]"),
This is precisely my point with https://github.com/reviewpad/reviewpad/pull/561/files#r1054839959. Users most likely will be confused to see this error message.

2022-12-21 21:31 UTC, marcelosousa commented on plugins/aladino/functions/selectFromJSON.go
> +		return aladino.BuildStringValue(""), nil
Shouldn't we return an error here? How will we differentiate between returning "" and an error?

2022-12-21 21:31 UTC, marcelosousa commented on plugins/aladino/functions/selectFromJSON_test.go
> +		},
Additionally, please test something that can return multiple results e.g. `"$.labels[*].name"`

2022-12-22 03:08 UTC, zolamk commented on plugins/aladino/functions/selectFromJSON.go
> +		return aladino.BuildStringValue(""), nil
this one was changed due to the suggestion here https://github.com/reviewpad/reviewpad/pull/563#discussion_r1054611095, what do you think?

2022-12-22 04:08 UTC, zolamk commented on plugins/aladino/functions/selectFromJSON_test.go
> +		},
I think this case should cover it https://github.com/reviewpad/reviewpad/blob/3a0b4b99115e0efb42088ca01477f9f0e1b2fdd3/plugins/aladino/functions/selectFromContext_test.go#L108

2022-12-22 11:44 UTC, marcelosousa commented on plugins/aladino/functions/selectFromJSON.go
> +		return aladino.BuildStringValue(""), nil
okay, thanks for pointing that out - this just need to be documented very well in the docs :)

2022-12-22 11:44 UTC, marcelosousa approved these changes
Let's go 🚀

2022-12-22 14:59 UTC, merged