feat: toNumber built-in function
reviewpad/reviewpad pull request #585
Opened 2022-12-24 11:44 UTC by zolamk

## Description
Adds a new built-in function `$toNumber`.

### Examples
- `$toNumber("5")`
- `$toNumber($selectFromContext("$.commits"))`

## Related issue

Closes #584 

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?
Unit tests

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2022-12-27 17:45 UTC, ferreiratiago requested changes

2022-12-27 17:45 UTC, ferreiratiago commented on plugins/aladino/functions/toNumber_test.go
> +				Func: "Atoi",
Why is this `Func` needed?

2022-12-27 17:45 UTC, ferreiratiago commented on plugins/aladino/functions/toNumber_test.go
> +				Err:  errors.New("invalid syntax"),
It there any reason for this to be capitalized? Can we put it in lowercase?

2022-12-27 17:53 UTC, ferreiratiago approved these changes

2022-12-27 17:53 UTC, ferreiratiago commented on plugins/aladino/functions/toNumber_test.go
> +				Func: "Atoi",
I see. These are the error properties.

2022-12-28 09:33 UTC, zolamk commented on plugins/aladino/functions/toNumber_test.go
> +				Err:  errors.New("invalid syntax"),
those are the errors properties

2022-12-28 13:50 UTC, merged