test: integration tests
reviewpad/reviewpad pull request #624
Opened 2023-01-19 12:38 UTC by zolamk

## Description
Adds integration tests to reviewpad that creates a PR on a Github repository and runs a set of reviewpad files on the pr.

## Related issue

Closes #614 

## Type of change

Improvements (non-breaking change without functionality)

## How was this tested?
Manual tests

## Checklist

- [x] I have performed a self-review of my code
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2023-01-24 10:37 UTC, ferreiratiago requested changes

2023-01-24 10:37 UTC, ferreiratiago commented on integration_test/integration_test.go
> +		"kitchen-sink": {
What does `kitchen-sink` means in this context?

2023-01-24 10:47 UTC, ferreiratiago commented
Can you please create an issue to add this `task integration-test` to the main CI?

2023-01-24 12:04 UTC, zolamk commented on integration_test/integration_test.go
> +	rawMostBuiltInsReviewpadFile, err := utils.ReadFile("./assets/most-built-ins-reviewpad.yml")
Yeah, makes sense to make it more descriptive

2023-01-24 12:16 UTC, zolamk commented on integration_test/integration_test.go
> +		"kitchen-sink": {
It just means to indicate a lot of the built-ins but better to rename it

2023-01-24 12:17 UTC, zolamk commented on integration_test/assets/utils/add.go
> +// @reviewpad-an: critical
Yeah, that's a mistake

2023-01-24 12:18 UTC, zolamk commented
> Can you please create an issue to add this `task integration-test` to the main CI?

Sure, of course.

2023-01-25 15:41 UTC, ferreiratiago approved these changes

2023-01-25 15:42 UTC, shay2025 approved these changes
Just some minor sentence changes suggestions 😉 but overall LGTM 🙌

2023-01-25 18:11 UTC, merged