feat: process check suite events
reviewpad/reviewpad pull request #630
Opened 2023-01-21 11:39 UTC by zolamk

## Description
Process `check_suite` events.

## Related issue

Closes #629 

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?
Unit and Manual tests.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2023-01-24 11:33 UTC, ferreiratiago requested changes

2023-01-24 11:33 UTC, ferreiratiago commented on handler/processors.go
> +	//  if the head is from a forked repository the pull_requests array will be empty on check suite events
```suggestion
	// When the check suite is from a head of a forked repository the pull_requests array will be empty
	// We need to fetch all the pull requests for the repository and find the one that matches the head sha
```

2023-01-24 11:33 UTC, ferreiratiago commented on handler/processors.go
> +		prs, err := getPullRequests(token, event.GetRepo().GetFullName())
Add a log before this line.

```go
log.Infof("no pull requests found in check suite event. fetching all pull requests for repository %v", event.GetRepo().GetFullName)
```

2023-01-24 11:33 UTC, ferreiratiago commented on handler/processors.go
> +		log.Infof("fetched %d pull requests", len(prs))
```suggestion
		log.Infof("no pull request found with the head sha %v", event.CheckSuite.GetHeadSHA())
```

2023-01-24 11:33 UTC, ferreiratiago commented on handler/processors.go
> +	}
Let's include this code inside an `else` block.

```suggestion
	} else {
		for _, pr := range event.CheckSuite.PullRequests {
			targetEntities = append(targetEntities, &TargetEntity{
				Kind:   PullRequest,
				Owner:  event.GetRepo().GetOwner().GetLogin(),
				Repo:   event.GetRepo().GetName(),
				Number: pr.GetNumber(),
			})
		}
	}
```

2023-01-24 11:47 UTC, zolamk commented on handler/processors.go
> +		log.Infof("fetched %d pull requests", len(prs))
I think some prs might still be found at this point right

2023-01-24 11:53 UTC, ferreiratiago commented on handler/processors.go
> +		log.Infof("fetched %d pull requests", len(prs))
I'm sorry. This comment was to be done on line [462](https://github.com/reviewpad/reviewpad/pull/630/files#diff-d07de10e776881f04ef3111a10250bfc72303ef3f0c71ffdd259c95632cbdfa3R462).

2023-01-25 09:45 UTC, ferreiratiago approved these changes

2023-01-25 09:45 UTC, merged