feat: extend config unauthorized err handling
reviewpad/reviewpad pull request #660
Opened 2023-02-01 12:18 UTC by shay2025

## Description

This pull request implements a feature to detect when a "404 Not Found" error is due to reviewpad not having access to the `reviewpad.yml` files that come from the `extends` property. The code checks the error message from the GitHub API after trying to download a file from a repository. If the error message is "Not Found" or "Repository access blocked", the error is likely due to reviewpad not being installed on a private repository. If it's not due to this reason, the error may be due to other factors.

It's worth noting that "404 Not Found" is a general HTTP error indicating that the requested resource could not be found on the server. On the other hand, "Repository access blocked" is a specific error message generated by GitHub indicating the user doesn't have sufficient permissions to access the requested repository.

GitHub uses "404 Not Found" instead of "Repository access blocked" when a user tries to download a file from a private repository they don't have access to because it fits the general case of a resource not being found on the server, regardless of the reason why it's unavailable. This allows for consistency in error messaging and avoids the need for different error messages for every possible reason a resource may be unavailable.

## Related issue

Closes #659 

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?

Manual tests and ran the `task check` cmd.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have run `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before the merge

2023-02-02 16:10 UTC, ferreiratiago requested changes

2023-02-02 16:10 UTC, ferreiratiago commented on engine/loader.go
> +		}
I would suggest setting the `Not found` option as the default one. This is to make sure we cover all cases regardless.

Also, create a common `contactUs` and make the message clear. Here's my suggestion:

```suggestion
		if responseErr, ok := err.(*github.ErrorResponse); ok && responseErr.Response.StatusCode == 404 {
			contactUs := "If you still encounter this error, please reach out to us at #help on https://reviewpad.com/discord for additional support."
			switch responseErr.Message {
			case "Repository access blocked":
				return nil, "", fmt.Errorf("we encountered an authorization error while processing the 'extends' property in your Reviewpad configuration. Please ensure that you have the Reviewpad GitHub App installed in all repositories you are trying to extend from. %s", contactUs)
			default:
				return nil, "", fmt.Errorf("we encountered an error while processing the 'extends' property in your Reviewpad configuration. This problem may be due to incorrect URL or unauthenticated access. Please ensure that you have Reviewpad GitHub App installed in all repositories you are trying to extend from and that the file name and path are correct. %s", contactUs)
			}
		}
```

2023-02-03 11:23 UTC, shay2025 commented
@ferreiratiago I decided to remove the `Repository access blocked`.
If a GitHub App tries to access a repository that it does not have access to, it will receive a "404 Not Found" error instead of the `Repository access blocked` error. This is because the "404 Not Found" error indicates that the requested resource could not be found on the server, whereas the "Repository access blocked" error is a more specific error message for when a user is not allowed to access a repository.

When a GitHub App receives a "404 Not Found" error, it means that the repository does not exist or that the App does not have sufficient permissions to access it.

GitHub Apps do not return the "Repository access block" error because the error message is intended for human users. When a user tries to access a repository that they do not have permission to, they see the "Repository access block" error message in their web browser or in the GitHub UI.

GitHub Apps, on the other hand, communicate with the GitHub API and receive responses in a machine-readable format. The "404 Not Found" error, which indicates that the requested resource could not be found, is a more appropriate error message for GitHub Apps to receive, as it can be easily processed and handled programmatically.

The "Repository access block" error message is intended to provide clear and concise information to human users about why they cannot access a repository, whereas the "404 Not Found" error provides the necessary information for GitHub Apps to determine that the repository is unavailable and to handle the error in an appropriate way.

2023-02-03 11:28 UTC, ferreiratiago approved these changes

2023-02-03 11:31 UTC, merged