fix: empty reviewpad report
reviewpad/reviewpad pull request #667
Opened 2023-02-03 14:46 UTC by shay2025

## Description

This pull request resolves the issue where the Reviewpad generates an empty report when the `mode` property is set to `verbose`. The solution handles the scenario where there are no actions executed by generating a report indicating this, otherwise, it presents a list of the actions executed.

## Related issue

Closes #654 

## Type of change

Bug fix (non-breaking change which fixes an issue)

## How was this tested?

Manual tests (described here https://www.notion.so/reviewpad/Reviewpad-generates-an-empty-report-e5eb16579ae84e2ab10f4464241a2dc9) and ran the `task check -f` cmd.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have run `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before the merge

2023-02-04 11:10 UTC, zolamk approved these changes
LGTM

2023-02-07 10:55 UTC, ferreiratiago requested changes
Minor improvement.

2023-02-07 10:55 UTC, ferreiratiago commented on lang/aladino/report.go
> +	} else {
We can return immediately here and allow for better reading.

```suggestion
	if len(program.GetProgramStatements()) == 0 {
		sb.WriteString("No actions triggered\n```\n")
		return sb.String()
	}
```

2023-02-07 10:59 UTC, shay2025 commented on lang/aladino/report.go
> +	} else {
Hmm, how will this allow for better reading, @ferreiratiago?
We are only handling the case of whether we have actions executed or not, after that the treatment is exactly the same.
I don't see the need to repeat the code unnecessarily 🤔

2023-02-07 11:11 UTC, ferreiratiago commented on lang/aladino/report.go
> +	} else {
It's the idea of [line of sight](https://speakerdeck.com/fedepaol/reducing-cognitive-load-yet-another-idiomatic-go-talk?slide=20) in order to reduce the cognitive load. In this case in particular is not a big deal but I think we should take this idea into account when making changes. You can check Federico [talk](https://fosdem.org/2023/schedule/event/goreducecognitive/) here.

2023-02-07 11:20 UTC, shay2025 commented on lang/aladino/report.go
> +	} else {
@ferreiratiago Yes, I am aware of the concept precept. However, being this such a simple case, adding more code may do the exact opposite and cause noise.

2023-02-07 11:28 UTC, ferreiratiago approved these changes

2023-02-07 11:28 UTC, merged