feat: GetOpenPullRequestsAsReviewer method
reviewpad/reviewpad pull request #694
Opened 2023-02-13 19:20 UTC by shay2025

## Description

This pull request implements the `GetOpenPullRequestsAsReviewer` that returns a set of the users and the total number of open pull requests where they are one of the requested reviewers.
If no users are provided, the users that will be taken into account are the repository collaborators.

## Related issue

Closes #682 

## Type of change

New feature (non-breaking change which adds functionality)

## How was this tested?

Manual tests by adding to the [`Run` method](https://github.com/reviewpad/reviewpad/blob/main/runner.go#L317) logs that printed the total number of pull requests for:
- 2 users;
- 1 user;
- no users.

The added logs:
```
// The user "dummypad" is one of the collaborators of the testing repository that has only one pull request to review
noUsers1, err := gitHubClient.GetOpenPullRequestsAsReviewer(ctx, targetEntity.Owner, targetEntity.Repo, nil)
if err != nil {
   fmt.Println(err)
}
fmt.Printf("NO USERS PROVIDED (NIL): %+v", noUsers1)

noUsers2, err := gitHubClient.GetOpenPullRequestsAsReviewer(ctx, targetEntity.Owner, targetEntity.Repo, []string{})
if err != nil {
   fmt.Println(err)
}
fmt.Printf("NO USERS PROVIDED (EMPTY ARRAY): %+v", noUsers2)

oneUser, err := gitHubClient.GetOpenPullRequestsAsReviewer(ctx, targetEntity.Owner, targetEntity.Repo, []string{"dummypad"})
if err != nil {
   fmt.Println(err)
}
fmt.Printf("ONE USER PROVIDED: %+v", oneUser)

// shay2025 is the owner of the testing repository
repoOwnerProvided, err := gitHubClient.GetOpenPullRequestsAsReviewer(ctx, targetEntity.Owner, targetEntity.Repo, []string{"dummypad", "shay2025"})
if err != nil {
   fmt.Println(err)
}
fmt.Printf("TWO USERS PROVIDED WHERE ONE OF THEM IS THE REPO OWNER: %+v", repoOwnerProvided)
```

Results:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/61353903/218553378-1c646dd3-bf8f-4ec0-b2c0-b4608a775235.png">

## Checklist

- [x] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or that my feature works 
- [x] I have run `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before the merge

2023-02-13 23:15 UTC, ferreiratiago requested changes

2023-02-13 23:15 UTC, ferreiratiago commented on codehost/github/pull_requests.go
> +			if collaborator.GetLogin() != owner {
Why are we removing the owner? I'm not sure why we want to remove the owner here.

2023-02-13 23:15 UTC, ferreiratiago commented on codehost/github/pull_requests.go
> +	numOfOpenPullRequestsByUser := make(map[string]int)
```suggestion
	totalOpenPullRequestsByUser := make(map[string]int)
```

2023-02-13 23:15 UTC, ferreiratiago commented on codehost/github/pull_requests.go
> +
I would suggest to combine all there struct into one and also to query only the necessary info:

```go
type LastFiftyOpenedPullRequestsQuery struct {
	Repository struct {
		PullRequests struct {
			Nodes []struct {
				ReviewRequests struct {
					Nodes []struct {
						AsUser struct {
							Login githubv4.String `graphql:"login"`
						} `graphql:"... on User"`
					}
				} `graphql:"reviewRequests(first: 50)"`
			}
		} `graphql:"pullRequests(states: OPEN, last: 50)"`
	} `graphql:"repository(owner: $owner, name: $name)"`
}
```

I'm afraid that this query is not enough for what we want. We need to confirm this with @fmallet. If user X has done 3 reviews and is still missing 1 review, the query above will return 1, when in fact the user is assigned as a reviewer to 4 pull requests. In this example, I am expecting user X to have the total number of pull requests assigned as a reviewer as 4, instead of 1. Is this correct @fmallet?

If true then we need to update the graphql query. Here's example of a query:

```graphql
{
  repository(owner: "reviewpad", name: "reviewpad") {
    pullRequests(states: OPEN, last: 50) {
      edges {
        node {
          reviewRequests(first: 50) {
            nodes {
              requestedReviewer {
                ... on User {
                  login
                }
              }
            }
          }
          reviews(first: 50) {
            nodes {
              author {
                login
              }
            }
          }
        }
      }
    }
  }
}
```

2023-02-13 23:15 UTC, ferreiratiago commented on codehost/github/pull_requests.go
> +	var result LastFiftyOpenedPullRequestsQuery
```suggestion
	var lastFiftyOpenedPullRequests LastFiftyOpenedPullRequestsQuery
```

2023-02-13 23:15 UTC, ferreiratiago commented on codehost/github/pull_requests.go
> +	for _, pr := range result.Repository.PullRequests.Nodes {
```suggestion
	for _, pullRequest := range result.Repository.PullRequests.Nodes {
```

2023-02-13 23:15 UTC, ferreiratiago commented on codehost/github/pull_requests.go
> +		for _, rr := range pr.ReviewRequests.Nodes {
```suggestion
		for _, reviewRequest := range pr.ReviewRequests.Nodes {
```

2023-02-13 23:15 UTC, ferreiratiago commented on codehost/github/pull_requests.go
> +			if requestedReviewer != owner && contains(usernames, requestedReviewer) {
Not sure why filtering the owner. Maybe I'm missing something.

2023-02-14 16:43 UTC, ferreiratiago requested changes

2023-02-14 16:43 UTC, ferreiratiago commented on codehost/github/pull_requests.go
> +	totalOpenPullRequestsByUser := make(map[string]int)
```suggestion
	totalOpenPRsAsReviewerByUser := make(map[string]int)
```

2023-02-14 16:43 UTC, ferreiratiago commented on codehost/github/pull_requests.go
> +	}
This function is a bit complex and hard to understand. Can we try to check for each pull request if the provided users are or not reviewers? e.g.

```go
	for _, pullRequest := range lastFiftyOpenedPullRequests.Repository.PullRequests.Nodes {
		for _, username := range usernames {
			if isPullRequestReviewer(pullRequest, username) {
				totalOpenPRsAsReviewerByUser[username]++
			}
		}
	}
```

Where `isPullRequestReviewer` could be something similar to this:

```go
func isPullRequestReviewer(pullRequest PullRequestsQuery, username string) bool {
	for _, reviewRequest := range pullRequest.ReviewRequests.Nodes {
		if string(reviewRequest.RequestedReviewer.AsUser.Login) == username {
			return true
		}
	}

	for _, review := range pullRequest.Reviews.Nodes {
		if string(review.Author.Login) == username {
			return true
		}
	}

	return false
}
```

And `PullRequestsQuery`

```go
type LastFiftyOpenedPullRequestsQuery struct {
	Repository struct {
		PullRequests struct {
			Nodes []PullRequestsQuery
		} `graphql:"pullRequests(states: OPEN, last: 50)"`
	} `graphql:"repository(owner: $owner, name: $name)"`
}
```

WDYT?

2023-02-14 16:47 UTC, shay2025 commented on codehost/github/pull_requests.go
> +	}
@ferreiratiago The suggestion for `PullRequestQuery` contradicts this suggestion https://github.com/reviewpad/reviewpad/pull/694#discussion_r1105110032

2023-02-14 17:33 UTC, ferreiratiago approved these changes

2023-02-14 17:38 UTC, merged