Allow a comment only once in a pull request
reviewpad/reviewpad pull request #7
Opened 2022-06-20 15:42 UTC by shay2025

This pull request introduces a new action called `$commentOnce()` that posts a comment in a pull request if a rule is followed and if the comment hasn't been made already.

It was added unit tests for this action and some mocks.

Closes #4

2022-06-21 08:41 UTC, marcelosousa requested changes
Some preliminary comments. The comments tagged with the 🚀 are deal breakers to the merge. 
**Pair review with @ferreiratiago**

2022-06-21 08:41 UTC, marcelosousa commented on go.mod
> +require (
Which version of go do you have? It seems that we have different version of go which is adding these require statements.

2022-06-21 08:41 UTC, marcelosousa commented on lang/aladino/parser.go
> +//line lang/aladino/parser.y:1
We need to understand why this generated file is different in your case.

2022-06-21 08:41 UTC, marcelosousa commented on plugins/aladino/actions.go
> +		commentAlreadyMade := *comment.Body == commentBody
I think we should improve this check. Imagine that the comment is 'LGTM' and someone else put this comment. This would prevent this built-in to act. As we do with the comments in the report, we need to annotate the comment body so that it is more clear that this comment was made by Reviewpad.

2022-06-21 08:41 UTC, marcelosousa commented on plugins/aladino/actions.go
> +	comments, _, err := e.GetClient().Issues.ListComments(e.GetCtx(), owner, repo, prNum, &github.IssueListCommentsOptions{})
I think this request is not paginated. We need to improve this. Check for example the function `getPullRequestFiles`.

2022-06-21 08:41 UTC, marcelosousa commented on plugins/aladino/actions_test.go
> +}
Please add a new line to the end of the file.

2022-06-21 08:41 UTC, marcelosousa commented on plugins/aladino/mocks.go
> +}
Same here.

2022-06-21 08:41 UTC, marcelosousa commented on plugins/aladino/mocks.go
> +// Proprietary and confidential
This LICENSE is not correct.

2022-06-21 08:41 UTC, marcelosousa commented on plugins/aladino/actions_test.go
> +// Proprietary and confidential
This LICENSE is not correct. We need to update your VSCode settings :-)

2022-06-21 09:33 UTC, shay2025 commented on plugins/aladino/actions.go
> +	comments, _, err := e.GetClient().Issues.ListComments(e.GetCtx(), owner, repo, prNum, &github.IssueListCommentsOptions{})
This request is also made in the function `FindReportComment`. Should it also be paginated?

2022-06-21 09:52 UTC, shay2025 commented on plugins/aladino/mocks.go
> +// Proprietary and confidential
There are many files around the repository that don't have the correct licence. We need to handle this.

2022-06-21 10:34 UTC, marcelosousa requested changes
Review of the tests.

2022-06-21 10:34 UTC, marcelosousa commented on plugins/aladino/mocks.go
> +	prNum := 6
It is confusing that this information is different than the one in L22.

2022-06-21 10:34 UTC, marcelosousa commented on plugins/aladino/actions_test.go
> +	err = commentOnceCode(*testEvalEnv, args)
```suggestion
	err = commentOnceCode(testEvalEnv, args)
```

2022-06-21 10:34 UTC, marcelosousa commented on plugins/aladino/actions_test.go
> +	err = commentOnceCode(*testEvalEnv, args)
```suggestion
	err = commentOnceCode(testEvalEnv, args)
```

2022-06-21 11:01 UTC, shay2025 commented on plugins/aladino/mocks.go
> +	prNum := 6
L22 refers to the pull request ID whereas this information refers to the pull request number which are different things.

2022-06-21 13:58 UTC, ferreiratiago requested changes
First iteration on the pull request. Still missing a review on the test files.

2022-06-21 17:43 UTC, ferreiratiago approved these changes
LGTM

2022-06-22 08:18 UTC, marcelosousa requested changes
Left some more comments! I think we are almost there 👍

2022-06-22 08:18 UTC, marcelosousa commented on plugins/aladino/actions.go
> +const reviewpadCommentAnnotation = "<!--@annotation-reviewpad-->"
This constant already exists in the report.go file. I think we should reuse it

2022-06-22 08:18 UTC, marcelosousa commented on plugins/aladino/actions.go
> +		isReviewpadComment := reviewpadCommentRegex.Match([]byte(*comment.Body))
I still think the best solution were would be to hash the contents of the comments instead of using regex Match. What do you think?

2022-06-22 08:18 UTC, marcelosousa commented on plugins/aladino/mocks.go
> +	prId := int64(prNum)
According to @shay2025 , the pull request number is different than the pull request id which makes sense. I think it is okay to leave it as is but it could also be confusing. WDYT?

2022-06-22 08:18 UTC, marcelosousa commented on plugins/aladino/mocks.go
> +// - Get pull request files (i.e. /repos/{owner}/{repo}/pulls/{pull_number})
The request here is the same as L111. I think there's a mistake here.

2022-06-22 08:18 UTC, marcelosousa commented on utils/github.go
> +func GetPullRequestComments(ctx context.Context, client *github.Client, owner string, repo string, number int) ([]*github.IssueComment, error) {
Since you have added this function, for consistency, please move the function `getPullRequestFiles` that lives in the file `lang/aladino/env.go` to here as well.

2022-06-22 10:38 UTC, ferreiratiago commented
Closing in favor of #24

2022-06-22 10:38 UTC, closed without merging