feat: improve random reviewer selection
reviewpad/reviewpad pull request #714
Opened 2023-02-19 09:51 UTC by zolamk

## Description
Improves the random reviewer selection for the `$assignCodeAuthorReviewers` built-in function.

## Related issue

Closes #709 

## Type of change

## How was this tested?
Unit and manual tests

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

2023-02-20 09:31 UTC, ferreiratiago requested changes

2023-02-20 09:31 UTC, ferreiratiago commented on plugins/aladino/actions/assignCodeAuthorReviewers.go
> +}
I would suggest to rename this function to `func filterAuthorsFromAssignees(assignees []*codehost.User, authors []string) []string {`. WDTY?

2023-02-20 09:31 UTC, ferreiratiago commented on plugins/aladino/actions/assignCodeAuthorReviewers.go
> +func isAssigneeEligibleToReview(
I understand the reason for this function. I would suggest keeping the function `isUserEligibleToReview` as it was and calling it also filtering the eligible users when assignee.

2023-02-20 09:31 UTC, ferreiratiago commented on plugins/aladino/actions/assignCodeAuthorReviewers.go
>  	}
I think we can improve this code for better understanding.
1. If there's no `selectedReviewers` then try to get then from `nonAuthorAvailableAssignees`.

```go
	if len(selectedReviewers) == 0 {
		for _, author := range nonAuthorAvailableAssignees {
			if isUserEligibleToReview(author, pr.PullRequest, reviewersToExclude, availableAssignees, totalOpenPRsAsReviewerByUser[author], maxAllowedAssignedReviews) {
				selectedReviewers = append(selectedReviewers, author)
			}
		}

		selectedReviewers = []string{selectedReviewers[rand.Intn(len(selectedReviewers))]}
	}
```

2. If there's no `selectedReviewers` then assign random reviewer.

```go
	if len(selectedReviewers) == 0 {
		return assignRandomReviewerCode(env, nil)
	}
```

WDYT?

2023-02-20 09:31 UTC, ferreiratiago commented on plugins/aladino/actions/assignCodeAuthorReviewers.go
> +		randomReviewer := selectedReviewers[utils.GenerateRandom(len(selectedReviewers))]
We should be using `rand.Intn` instead of `utils.GenerateRandom`.

2023-02-20 19:13 UTC, ferreiratiago requested changes

2023-02-20 19:13 UTC, ferreiratiago commented on plugins/aladino/actions/assignCodeAuthorReviewers.go
> +}
Suggestion for better reading.

```suggestion
func getRandomReviewers(reviewers []string, total int) []string {
	if total >= len(reviewers) {
		return reviewers
	}

	selectedReviewers := make([]string, total)

	for i := 0; i < total; i++ {
		randIndex := rand.Intn(len(reviewers))
		selectedReviewers[i] = reviewers[randIndex]

		reviewers = append(reviewers[:randIndex], reviewers[randIndex+1:]...)
	}

	return selectedReviewers
}
```

2023-02-20 19:13 UTC, ferreiratiago commented on plugins/aladino/actions/assignCodeAuthorReviewers.go
> +		}
My understanding may be wrong but if we are not able to assign random reviewers from the available assignees why would `assignRandomReviewerCode` work since it does the same? 😄 I think we can remove this piece of code.

2023-02-21 03:49 UTC, zolamk commented on plugins/aladino/actions/assignCodeAuthorReviewers.go
> +		}
The thing is if none of the code authors are eligible then we try to find eligible reviewers from the available assignees if that still doesn't give us any reviewers then we pick a random reviewer regardless of their eligibility right, I think it's step 6 of the specification, what do you think?

2023-02-21 03:50 UTC, zolamk commented on plugins/aladino/actions/assignCodeAuthorReviewers.go
> +		}
the `$assignRandomReviewer` built-in doesn't have any eligibility check so it will just pick a random user right

2023-02-21 08:04 UTC, ferreiratiago commented on plugins/aladino/actions/assignCodeAuthorReviewers.go
> +		}
Indeed @zolamk That is correct :)

2023-02-21 08:10 UTC, ferreiratiago approved these changes

2023-02-21 08:10 UTC, merged