Add unit tests for `$assignes` function builtin
reviewpad/reviewpad pull request #73
Opened 2022-07-06 16:12 UTC by shay2025

This pull request adds unit tests for `$assignes` function builtin.

2022-07-07 09:30 UTC, marcelosousa commented
@shay2025 there's a typo - `assignes` -> `assignees`

2022-07-07 15:40 UTC, ferreiratiago requested changes
The test needs to be refactored. Please have a look at the comment :)

2022-07-07 15:40 UTC, ferreiratiago commented on plugins/aladino/functions/assignees_test.go
> +func TestAssignees(t *testing.T) {
We need to improve this test in order not to rely on the `getDefaultMockPullRequestDetails`.

For instance, if we remove `Assignees: []*github.User{{Login: github.String("jane")}}` from the mock, this test will continue to pass but it's not performing a proper test.

We need to mock our tests based on `getDefaultMockPullRequestDetails` but always changes whatever we are testing to make sure what when the test fails is for the right reason.

2022-07-11 09:39 UTC, reviewpad-team commented
<!--@annotation-reviewpad-report-->
**Reviewpad Report**

**:information_source: Messages**
* If you are adding or updating a built-in, please do not forget to update the [docs](https://github.com/reviewpad/docs)
* If you have added a new function or action do not forget to include it in the built-in list!

2022-07-11 12:36 UTC, ferreiratiago approved these changes
LGTM

2022-07-11 15:17 UTC, merged