feat: compact format for if, then and actions
reviewpad/reviewpad pull request #824
Opened 2023-04-08 09:45 UTC by zolamk

## Description
Introduces a compact form for `if`, `then` and `actions` fields in reviewpad file.
```
workflows:
  - name: add-label
    if: '$size() <= 30'
    then: '$addLabel("small")'

pipelines:
  - name: renovate-bot
    trigger: $author() == "renovate[bot]"
    stages:
      - actions: $assignAssignees($group("owners"), 1)
        until: $assignees() != []
```

## Related issue

Closes reviewpad/raas-common#103

## Type of change

**New feature** (non-breaking change which adds functionality)

## How was this tested?
Manual and Unit tests.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix/feature works (if applicable) and have tested properly
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

**Ask**: this pull request requires a code review before merge

2023-04-12 14:26 UTC, ferreiratiago requested changes

2023-04-12 14:26 UTC, ferreiratiago commented on engine/inline_rules_normalizer.go
> +	case string:
Can we add some comments for each case? If my understanding is correct:

```go
switch r := rawRule.(type) {
// Specificition of inline rule or rule name.
case string:
	// ...
// List of rules inline rules or rule names.
case []any:
	// ...
// Specificition of "rule" with/without "extra-actions".
case map[string]any:
	// ...
default:
	return nil, nil, fmt.Errorf("unknown rule type %T", r)
}
```

2023-04-12 14:26 UTC, ferreiratiago commented on engine/inline_rules_normalizer.go
> +		rule = decodeRule(r)
If my understanding is correct being string can mean the name of a specified rule under `rules`, which means that this decode is not correct. It works because on line [136](https://github.com/reviewpad/reviewpad/pull/824/files#diff-ea18868fc6cfa08e95023e74934900b2af69a653d53a65a962abe70616a132f6R136) we look for all rules and we will end up with the correct spec.

We don't need to correct this since it's working and we will be addressing this issue later.


Just wanted to create awareness.

2023-04-12 14:26 UTC, ferreiratiago commented on engine/inline_rules_normalizer.go
> +	// we need to check rule is not nil if we are processing a list of rules
No need for this comment.

2023-04-12 14:26 UTC, ferreiratiago commented on engine/inline_rules_normalizer.go
> +	// we need to check workflowRule is not nil if we are processing a list of rules
No need for this comment.

2023-04-12 14:26 UTC, ferreiratiago commented on engine/inline_rules_normalizer.go
> +func processCompactRules(rawRule any, currentRules []PadRule) ([]PadRule, []PadWorkflowRule, error) {
IMO this name is not the best since we are processing all rules regardless of being compact. I would suggest renaming to `normalizeRules`. Also, to add a comment to the function explaining what it does.

2023-04-12 14:26 UTC, ferreiratiago commented on engine/inline_rules_normalizer.go
> +func processCompactActions(nonNormalizedActions any) ([]string, error) {
The same here. I would suggest renaming to `normalizeActions` and to add a comment explaining what the function does.

2023-04-12 14:56 UTC, zolamk commented on engine/inline_rules_normalizer.go
> +	case nil:
that's in case the workflow doesn't have any actions but only extra actions associated with the rules

2023-04-12 15:13 UTC, zolamk commented on engine/inline_rules_normalizer.go
> +		rule = decodeRule(r)
Yes, this is just creating a rule structure using the spec as a name and we verify it doesn't exist at a later stage, it was a way of avoiding having duplicate rules if the same spec is repated

2023-04-13 08:42 UTC, ferreiratiago approved these changes

2023-04-13 08:43 UTC, merged