Add $hasCodePattern unit tests
reviewpad/reviewpad pull request #94
Opened 2022-07-11 12:23 UTC by shay2025

## Description

This pull request introduces `$hasCodePattern` unit tests.

## Related issue

*None*

## Type of change

Improvements (non-breaking change without functionality)

## How was this tested?

Ran `task test` command.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have ran `task check -f` and have no issues

2022-07-11 12:24 UTC, reviewpad-team commented
<!--@annotation-reviewpad-report-->
**Reviewpad Report**

**:information_source: Messages**
* If you are adding or updating a built-in, please do not forget to update the [docs](https://github.com/reviewpad/docs)
* If you have added a new function or action do not forget to include it in the built-in list!

2022-07-11 12:24 UTC, shay2025 commented on plugins/aladino/functions/hasCodePattern_test.go
> +	)
This is to avoid unnecessary computation since we have mocked pull request files list.

2022-07-11 12:25 UTC, shay2025 commented on plugins/aladino/functions/hasCodePattern_test.go
> +    )
Same as https://github.com/reviewpad/reviewpad/pull/94/files#r917868598

2022-07-12 08:25 UTC, ferreiratiago requested changes
Please have a look at the comments :)

2022-07-12 08:25 UTC, ferreiratiago commented on plugins/aladino/functions/hasCodePattern_test.go
> +	)
I'm not sure what you mean with this comment. Can you please clarify?

2022-07-12 08:25 UTC, ferreiratiago commented on plugins/aladino/functions/hasCodePattern_test.go
> +func TestHasCodePattern_WhenFileHasQueryError(t *testing.T) {
Suggestion `TestHasCodePattern_WhenPatternIsInvalid`

2022-07-12 09:21 UTC, shay2025 commented on plugins/aladino/functions/hasCodePattern_test.go
> +	)
When we are creating a new env we get the pull request files and process them in order to add them to the patch map. Since we have the pull request files in the default mocks which consists, at the moment, of 5 files, we don't need to perform the processing of all this files so we overwrite the default mock pull request changed files so we only have to deal with one file.
https://github.com/reviewpad/reviewpad/blob/0bf53f27a8f0384a32fecd128cd44f03034390e2/lang/aladino/env.go#L97-L123

2022-07-12 18:58 UTC, ferreiratiago approved these changes
LGTM

2022-07-13 09:50 UTC, merged